namespace OculusTrayTool
{
	// Token: 0x0200001A RID: 26
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmCreateEditProfile : global::System.Windows.Forms.Form
	{
		// Token: 0x060001E1 RID: 481 RVA: 0x00009224 File Offset: 0x00007424
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060001E2 RID: 482 RVA: 0x00009274 File Offset: 0x00007474
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::OculusTrayTool.frmCreateEditProfile));
			this.ComboCPU = new global::System.Windows.Forms.ComboBox();
			this.TextDisplayName = new global::System.Windows.Forms.TextBox();
			this.ComboASW = new global::System.Windows.Forms.ComboBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.ComboMethod = new global::System.Windows.Forms.ComboBox();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.ComboBoxEnabled = new global::System.Windows.Forms.ComboBox();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label33 = new global::System.Windows.Forms.Label();
			this.ComboBox8 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox9 = new global::System.Windows.Forms.ComboBox();
			this.Label37 = new global::System.Windows.Forms.Label();
			this.PictureBox11 = new global::System.Windows.Forms.PictureBox();
			this.NumericUpDown3 = new global::System.Windows.Forms.NumericUpDown();
			this.NumericUpDown4 = new global::System.Windows.Forms.NumericUpDown();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.TextBoxComment = new global::System.Windows.Forms.TextBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.ComboSS = new global::System.Windows.Forms.ComboBox();
			this.PictureBox10 = new global::System.Windows.Forms.PictureBox();
			this.ComboAGPS = new global::System.Windows.Forms.ComboBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.PictureBox9 = new global::System.Windows.Forms.PictureBox();
			this.ComboMirror = new global::System.Windows.Forms.ComboBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.PictureBox8 = new global::System.Windows.Forms.PictureBox();
			this.TextBoxPath = new global::System.Windows.Forms.TextBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.NumericUpDown2 = new global::System.Windows.Forms.NumericUpDown();
			this.PictureBox7 = new global::System.Windows.Forms.PictureBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.NumericUpDown1 = new global::System.Windows.Forms.NumericUpDown();
			this.PictureBox6 = new global::System.Windows.Forms.PictureBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.PictureBox5 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox4 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.GroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox11).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox10).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox9).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox8).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox7).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox6).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox5).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			base.SuspendLayout();
			this.ComboCPU.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.ComboCPU.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboCPU.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboCPU.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ComboCPU.FormattingEnabled = true;
			this.ComboCPU.Items.AddRange(new object[] { "Default", "Normal", "Above Normal", "High" });
			this.ComboCPU.Location = new global::System.Drawing.Point(103, 149);
			this.ComboCPU.Name = "ComboCPU";
			this.ComboCPU.Size = new global::System.Drawing.Size(208, 23);
			this.ComboCPU.TabIndex = 18;
			this.TextDisplayName.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.TextDisplayName.Location = new global::System.Drawing.Point(104, 18);
			this.TextDisplayName.Name = "TextDisplayName";
			this.TextDisplayName.Size = new global::System.Drawing.Size(208, 21);
			this.TextDisplayName.TabIndex = 17;
			this.ComboASW.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.ComboASW.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboASW.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboASW.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ComboASW.FormattingEnabled = true;
			this.ComboASW.Items.AddRange(new object[] { "Auto", "Off", "45 Hz", "30 Hz", "18 Hz", "45 Hz forced", "Adaptive" });
			this.ComboASW.Location = new global::System.Drawing.Point(103, 89);
			this.ComboASW.Name = "ComboASW";
			this.ComboASW.Size = new global::System.Drawing.Size(208, 23);
			this.ComboASW.TabIndex = 16;
			this.Label1.AutoSize = true;
			this.Label1.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label1.Location = new global::System.Drawing.Point(14, 24);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(62, 13);
			this.Label1.TabIndex = 19;
			this.Label1.Text = "Game/App:";
			this.Label2.AutoSize = true;
			this.Label2.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label2.Location = new global::System.Drawing.Point(14, 57);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(84, 13);
			this.Label2.TabIndex = 20;
			this.Label2.Text = "Super Sampling:";
			this.Label3.AutoSize = true;
			this.Label3.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label3.Location = new global::System.Drawing.Point(14, 94);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(65, 13);
			this.Label3.TabIndex = 21;
			this.Label3.Text = "ASW Mode:";
			this.Label4.AutoSize = true;
			this.Label4.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label4.Location = new global::System.Drawing.Point(14, 154);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(66, 13);
			this.Label4.TabIndex = 22;
			this.Label4.Text = "CPU Priority:";
			this.Label5.AutoSize = true;
			this.Label5.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label5.Location = new global::System.Drawing.Point(14, 216);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(56, 13);
			this.Label5.TabIndex = 24;
			this.Label5.Text = "Detection:";
			this.ComboMethod.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.ComboMethod.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboMethod.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboMethod.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ComboMethod.FormattingEnabled = true;
			this.ComboMethod.Items.AddRange(new object[] { "WMI", "Timer" });
			this.ComboMethod.Location = new global::System.Drawing.Point(103, 211);
			this.ComboMethod.Name = "ComboMethod";
			this.ComboMethod.Size = new global::System.Drawing.Size(208, 23);
			this.ComboMethod.TabIndex = 25;
			this.GroupBox1.Controls.Add(this.ComboBoxEnabled);
			this.GroupBox1.Controls.Add(this.Label15);
			this.GroupBox1.Controls.Add(this.Label33);
			this.GroupBox1.Controls.Add(this.ComboBox8);
			this.GroupBox1.Controls.Add(this.ComboBox9);
			this.GroupBox1.Controls.Add(this.Label37);
			this.GroupBox1.Controls.Add(this.PictureBox11);
			this.GroupBox1.Controls.Add(this.NumericUpDown3);
			this.GroupBox1.Controls.Add(this.NumericUpDown4);
			this.GroupBox1.Controls.Add(this.Label14);
			this.GroupBox1.Controls.Add(this.Label13);
			this.GroupBox1.Controls.Add(this.Label12);
			this.GroupBox1.Controls.Add(this.TextBoxComment);
			this.GroupBox1.Controls.Add(this.Label11);
			this.GroupBox1.Controls.Add(this.ComboSS);
			this.GroupBox1.Controls.Add(this.PictureBox10);
			this.GroupBox1.Controls.Add(this.ComboAGPS);
			this.GroupBox1.Controls.Add(this.Label10);
			this.GroupBox1.Controls.Add(this.PictureBox9);
			this.GroupBox1.Controls.Add(this.ComboMirror);
			this.GroupBox1.Controls.Add(this.Label9);
			this.GroupBox1.Controls.Add(this.ComboBox1);
			this.GroupBox1.Controls.Add(this.Button3);
			this.GroupBox1.Controls.Add(this.PictureBox8);
			this.GroupBox1.Controls.Add(this.TextBoxPath);
			this.GroupBox1.Controls.Add(this.Label8);
			this.GroupBox1.Controls.Add(this.NumericUpDown2);
			this.GroupBox1.Controls.Add(this.PictureBox7);
			this.GroupBox1.Controls.Add(this.Label7);
			this.GroupBox1.Controls.Add(this.NumericUpDown1);
			this.GroupBox1.Controls.Add(this.PictureBox6);
			this.GroupBox1.Controls.Add(this.Label6);
			this.GroupBox1.Controls.Add(this.PictureBox5);
			this.GroupBox1.Controls.Add(this.PictureBox4);
			this.GroupBox1.Controls.Add(this.PictureBox3);
			this.GroupBox1.Controls.Add(this.PictureBox2);
			this.GroupBox1.Controls.Add(this.PictureBox1);
			this.GroupBox1.Controls.Add(this.TextDisplayName);
			this.GroupBox1.Controls.Add(this.ComboMethod);
			this.GroupBox1.Controls.Add(this.ComboASW);
			this.GroupBox1.Controls.Add(this.Label5);
			this.GroupBox1.Controls.Add(this.ComboCPU);
			this.GroupBox1.Controls.Add(this.Label4);
			this.GroupBox1.Controls.Add(this.Label3);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Controls.Add(this.Label2);
			this.GroupBox1.Location = new global::System.Drawing.Point(12, 2);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.Size = new global::System.Drawing.Size(754, 292);
			this.GroupBox1.TabIndex = 26;
			this.GroupBox1.TabStop = false;
			this.ComboBoxEnabled.FormattingEnabled = true;
			this.ComboBoxEnabled.Items.AddRange(new object[] { "Yes", "No" });
			this.ComboBoxEnabled.Location = new global::System.Drawing.Point(550, 246);
			this.ComboBoxEnabled.Name = "ComboBoxEnabled";
			this.ComboBoxEnabled.Size = new global::System.Drawing.Size(162, 21);
			this.ComboBoxEnabled.TabIndex = 66;
			this.Label15.AutoSize = true;
			this.Label15.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label15.Location = new global::System.Drawing.Point(415, 249);
			this.Label15.Name = "Label15";
			this.Label15.Size = new global::System.Drawing.Size(49, 13);
			this.Label15.TabIndex = 65;
			this.Label15.Text = "Enabled:";
			this.Label33.AutoSize = true;
			this.Label33.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label33.Location = new global::System.Drawing.Point(415, 140);
			this.Label33.Name = "Label33";
			this.Label33.Size = new global::System.Drawing.Size(130, 13);
			this.Label33.TabIndex = 61;
			this.Label33.Text = "Force MipMap Generation";
			this.Label33.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.ComboBox8.BackColor = global::System.Drawing.Color.AliceBlue;
			this.ComboBox8.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox8.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboBox8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ComboBox8.FormattingEnabled = true;
			this.ComboBox8.Items.AddRange(new object[] { "True", "False" });
			this.ComboBox8.Location = new global::System.Drawing.Point(551, 135);
			this.ComboBox8.Name = "ComboBox8";
			this.ComboBox8.Size = new global::System.Drawing.Size(162, 24);
			this.ComboBox8.TabIndex = 62;
			this.ComboBox9.BackColor = global::System.Drawing.Color.AliceBlue;
			this.ComboBox9.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox9.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboBox9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ComboBox9.FormattingEnabled = true;
			this.ComboBox9.Items.AddRange(new object[]
			{
				"0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
				"10", "11", "12", "13", "14", "15", "16", "17", "18", "19",
				"20"
			});
			this.ComboBox9.Location = new global::System.Drawing.Point(551, 173);
			this.ComboBox9.Name = "ComboBox9";
			this.ComboBox9.Size = new global::System.Drawing.Size(162, 24);
			this.ComboBox9.TabIndex = 64;
			this.Label37.AutoSize = true;
			this.Label37.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label37.Location = new global::System.Drawing.Point(415, 178);
			this.Label37.Name = "Label37";
			this.Label37.Size = new global::System.Drawing.Size(99, 13);
			this.Label37.TabIndex = 63;
			this.Label37.Text = "Offset MipMap Bias";
			this.Label37.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.PictureBox11.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox11.Image");
			this.PictureBox11.Location = new global::System.Drawing.Point(729, 99);
			this.PictureBox11.Name = "PictureBox11";
			this.PictureBox11.Size = new global::System.Drawing.Size(19, 20);
			this.PictureBox11.TabIndex = 60;
			this.PictureBox11.TabStop = false;
			this.ToolTip1.SetToolTip(this.PictureBox11, componentResourceManager.GetString("PictureBox11.ToolTip"));
			this.NumericUpDown3.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.NumericUpDown3.DecimalPlaces = 2;
			this.NumericUpDown3.Increment = new decimal(new int[] { 1, 0, 0, 131072 });
			this.NumericUpDown3.Location = new global::System.Drawing.Point(562, 97);
			global::System.Windows.Forms.NumericUpDown numericUpDown = this.NumericUpDown3;
			int[] array = new int[4];
			array[0] = 2;
			numericUpDown.Maximum = new decimal(array);
			this.NumericUpDown3.Name = "NumericUpDown3";
			this.NumericUpDown3.Size = new global::System.Drawing.Size(45, 20);
			this.NumericUpDown3.TabIndex = 59;
			this.NumericUpDown4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.NumericUpDown4.DecimalPlaces = 2;
			this.NumericUpDown4.Increment = new decimal(new int[] { 1, 0, 0, 131072 });
			this.NumericUpDown4.Location = new global::System.Drawing.Point(669, 97);
			global::System.Windows.Forms.NumericUpDown numericUpDown2 = this.NumericUpDown4;
			int[] array2 = new int[4];
			array2[0] = 2;
			numericUpDown2.Maximum = new decimal(array2);
			this.NumericUpDown4.Name = "NumericUpDown4";
			this.NumericUpDown4.Size = new global::System.Drawing.Size(45, 20);
			this.NumericUpDown4.TabIndex = 56;
			this.Label14.AutoSize = true;
			this.Label14.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label14.Location = new global::System.Drawing.Point(621, 99);
			this.Label14.Name = "Label14";
			this.Label14.Size = new global::System.Drawing.Size(42, 13);
			this.Label14.TabIndex = 55;
			this.Label14.Text = "Vertical";
			this.Label13.AutoSize = true;
			this.Label13.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label13.Location = new global::System.Drawing.Point(502, 99);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(54, 13);
			this.Label13.TabIndex = 54;
			this.Label13.Text = "Horizontal";
			this.Label12.AutoSize = true;
			this.Label12.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label12.Location = new global::System.Drawing.Point(415, 99);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(73, 13);
			this.Label12.TabIndex = 53;
			this.Label12.Text = "FoV Multiplier:";
			this.TextBoxComment.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.TextBoxComment.Location = new global::System.Drawing.Point(550, 211);
			this.TextBoxComment.Name = "TextBoxComment";
			this.TextBoxComment.Size = new global::System.Drawing.Size(162, 21);
			this.TextBoxComment.TabIndex = 51;
			this.Label11.AutoSize = true;
			this.Label11.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label11.Location = new global::System.Drawing.Point(415, 216);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(54, 13);
			this.Label11.TabIndex = 52;
			this.Label11.Text = "Comment:";
			this.ComboSS.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.ComboSS.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboSS.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ComboSS.FormattingEnabled = true;
			this.ComboSS.Items.AddRange(new object[]
			{
				"0", "0.7", "0.75", "0.8", "0.85", "0.9", "0.95", "1.0", "1.05", "1.1",
				"1.15", "1.2", "1.25", "1.3", "1.35", "1.4", "1.45", "1.5", "1.55", "1.6",
				"1.65", "1.7", "1.75", "1.8", "1.85", "1.9", "1.95", "2.0", "2.05", "2.1",
				"2.15", "2.2", "2.25", "2.3", "2.35", "2.4", "2.45", "2.5"
			});
			this.ComboSS.Location = new global::System.Drawing.Point(103, 52);
			this.ComboSS.Name = "ComboSS";
			this.ComboSS.Size = new global::System.Drawing.Size(208, 23);
			this.ComboSS.Sorted = true;
			this.ComboSS.TabIndex = 29;
			this.ComboSS.TabStop = false;
			this.PictureBox10.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox10.Image");
			this.PictureBox10.Location = new global::System.Drawing.Point(729, 55);
			this.PictureBox10.Name = "PictureBox10";
			this.PictureBox10.Size = new global::System.Drawing.Size(19, 20);
			this.PictureBox10.TabIndex = 46;
			this.PictureBox10.TabStop = false;
			this.ToolTip1.SetToolTip(this.PictureBox10, "Enables or Disables Adaptive GPU Scaling. Setting this to Off might improve the experience in some games.");
			this.ComboAGPS.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.ComboAGPS.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboAGPS.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ComboAGPS.FormattingEnabled = true;
			this.ComboAGPS.Items.AddRange(new object[] { "Off", "On" });
			this.ComboAGPS.Location = new global::System.Drawing.Point(505, 51);
			this.ComboAGPS.Name = "ComboAGPS";
			this.ComboAGPS.Size = new global::System.Drawing.Size(208, 23);
			this.ComboAGPS.TabIndex = 45;
			this.Label10.AutoSize = true;
			this.Label10.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label10.Location = new global::System.Drawing.Point(415, 56);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(71, 13);
			this.Label10.TabIndex = 44;
			this.Label10.Text = "GPU Scaling:";
			this.PictureBox9.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox9.Image");
			this.PictureBox9.Location = new global::System.Drawing.Point(729, 17);
			this.PictureBox9.Name = "PictureBox9";
			this.PictureBox9.Size = new global::System.Drawing.Size(19, 20);
			this.PictureBox9.TabIndex = 43;
			this.PictureBox9.TabStop = false;
			this.ToolTip1.SetToolTip(this.PictureBox9, "Sets the window state of the app when it is launched.");
			this.ComboMirror.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.ComboMirror.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboMirror.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ComboMirror.FormattingEnabled = true;
			this.ComboMirror.Items.AddRange(new object[] { "Default", "Minimized", "Forced" });
			this.ComboMirror.Location = new global::System.Drawing.Point(505, 16);
			this.ComboMirror.Name = "ComboMirror";
			this.ComboMirror.Size = new global::System.Drawing.Size(208, 23);
			this.ComboMirror.TabIndex = 42;
			this.Label9.AutoSize = true;
			this.Label9.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label9.Location = new global::System.Drawing.Point(416, 21);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(73, 13);
			this.Label9.TabIndex = 41;
			this.Label9.Text = "Screen Mirror:";
			this.ComboBox1.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.ComboBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Location = new global::System.Drawing.Point(104, 17);
			this.ComboBox1.Name = "ComboBox1";
			this.ComboBox1.Size = new global::System.Drawing.Size(208, 23);
			this.ComboBox1.Sorted = true;
			this.ComboBox1.TabIndex = 29;
			this.ComboBox1.Text = "- Select Game -";
			this.ComboBox1.Visible = false;
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button3.Location = new global::System.Drawing.Point(318, 19);
			this.Button3.Name = "Button3";
			this.Button3.Size = new global::System.Drawing.Size(26, 21);
			this.Button3.TabIndex = 29;
			this.Button3.Text = "..";
			this.ToolTip1.SetToolTip(this.Button3, "Manually browse for a game if it is not found in the list, or change profile .exe, e.g. the process that Oculus TrayTool will monitor.");
			this.Button3.UseVisualStyleBackColor = true;
			this.PictureBox8.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox8.Image");
			this.PictureBox8.Location = new global::System.Drawing.Point(349, 249);
			this.PictureBox8.Name = "PictureBox8";
			this.PictureBox8.Size = new global::System.Drawing.Size(19, 20);
			this.PictureBox8.TabIndex = 40;
			this.PictureBox8.TabStop = false;
			this.ToolTip1.SetToolTip(this.PictureBox8, "The path to the executable that OTT should monitor.");
			this.TextBoxPath.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.TextBoxPath.Location = new global::System.Drawing.Point(104, 249);
			this.TextBoxPath.Name = "TextBoxPath";
			this.TextBoxPath.Size = new global::System.Drawing.Size(208, 21);
			this.TextBoxPath.TabIndex = 38;
			this.Label8.AutoSize = true;
			this.Label8.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label8.Location = new global::System.Drawing.Point(14, 254);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(56, 13);
			this.Label8.TabIndex = 39;
			this.Label8.Text = "EXE Path:";
			this.NumericUpDown2.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.NumericUpDown2.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.NumericUpDown2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.NumericUpDown2.Location = new global::System.Drawing.Point(103, 178);
			this.NumericUpDown2.Name = "NumericUpDown2";
			this.NumericUpDown2.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.NumericUpDown2.Size = new global::System.Drawing.Size(208, 18);
			this.NumericUpDown2.TabIndex = 35;
			this.NumericUpDown2.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.NumericUpDown2.UpDownAlign = global::System.Windows.Forms.LeftRightAlignment.Left;
			this.PictureBox7.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox7.Image");
			this.PictureBox7.Location = new global::System.Drawing.Point(349, 176);
			this.PictureBox7.Name = "PictureBox7";
			this.PictureBox7.Size = new global::System.Drawing.Size(19, 20);
			this.PictureBox7.TabIndex = 37;
			this.PictureBox7.TabStop = false;
			this.ToolTip1.SetToolTip(this.PictureBox7, "Sets the delay before applying CPU Priority. Some games and apps require a bit more time to start up to successfully change PCU Priority.");
			this.Label7.AutoSize = true;
			this.Label7.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label7.Location = new global::System.Drawing.Point(25, 180);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(56, 13);
			this.Label7.TabIndex = 36;
			this.Label7.Text = "Set Delay:";
			this.NumericUpDown1.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.NumericUpDown1.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.NumericUpDown1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.NumericUpDown1.Location = new global::System.Drawing.Point(103, 118);
			this.NumericUpDown1.Name = "NumericUpDown1";
			this.NumericUpDown1.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.NumericUpDown1.Size = new global::System.Drawing.Size(208, 18);
			this.NumericUpDown1.TabIndex = 29;
			this.NumericUpDown1.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.NumericUpDown1.UpDownAlign = global::System.Windows.Forms.LeftRightAlignment.Left;
			this.PictureBox6.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox6.Image");
			this.PictureBox6.Location = new global::System.Drawing.Point(349, 116);
			this.PictureBox6.Name = "PictureBox6";
			this.PictureBox6.Size = new global::System.Drawing.Size(19, 20);
			this.PictureBox6.TabIndex = 34;
			this.PictureBox6.TabStop = false;
			this.ToolTip1.SetToolTip(this.PictureBox6, "Sets the delay before applying ASW. Some games and apps require a bit more time to start up to successfully change ASW.");
			this.Label6.AutoSize = true;
			this.Label6.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label6.Location = new global::System.Drawing.Point(20, 119);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(56, 13);
			this.Label6.TabIndex = 33;
			this.Label6.Text = "Set Delay:";
			this.PictureBox5.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox5.Image");
			this.PictureBox5.Location = new global::System.Drawing.Point(349, 214);
			this.PictureBox5.Name = "PictureBox5";
			this.PictureBox5.Size = new global::System.Drawing.Size(19, 20);
			this.PictureBox5.TabIndex = 31;
			this.PictureBox5.TabStop = false;
			this.ToolTip1.SetToolTip(this.PictureBox5, componentResourceManager.GetString("PictureBox5.ToolTip"));
			this.PictureBox4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox4.Image");
			this.PictureBox4.Location = new global::System.Drawing.Point(349, 147);
			this.PictureBox4.Name = "PictureBox4";
			this.PictureBox4.Size = new global::System.Drawing.Size(19, 20);
			this.PictureBox4.TabIndex = 30;
			this.PictureBox4.TabStop = false;
			this.ToolTip1.SetToolTip(this.PictureBox4, "Makes Windows give this app a bit higher priority over other system resources. Can improve performance.");
			this.PictureBox3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox3.Image");
			this.PictureBox3.Location = new global::System.Drawing.Point(349, 87);
			this.PictureBox3.Name = "PictureBox3";
			this.PictureBox3.Size = new global::System.Drawing.Size(19, 20);
			this.PictureBox3.TabIndex = 29;
			this.PictureBox3.TabStop = false;
			this.ToolTip1.SetToolTip(this.PictureBox3, "Sets the mode for Asynchronous Space Warp (ASW). This should usualy be set to Auto unless you experience issues.");
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			this.PictureBox2.Location = new global::System.Drawing.Point(349, 55);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(19, 20);
			this.PictureBox2.TabIndex = 28;
			this.PictureBox2.TabStop = false;
			this.ToolTip1.SetToolTip(this.PictureBox2, componentResourceManager.GetString("PictureBox2.ToolTip"));
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(349, 20);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(19, 20);
			this.PictureBox1.TabIndex = 27;
			this.PictureBox1.TabStop = false;
			this.ToolTip1.SetToolTip(this.PictureBox1, componentResourceManager.GetString("PictureBox1.ToolTip"));
			this.ToolTip1.AutoPopDelay = 15000;
			this.ToolTip1.InitialDelay = 200;
			this.ToolTip1.ReshowDelay = 100;
			this.Button1.Enabled = false;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Button1.Location = new global::System.Drawing.Point(714, 300);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(52, 23);
			this.Button1.TabIndex = 27;
			this.Button1.Text = "OK";
			this.Button1.UseVisualStyleBackColor = true;
			this.Button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button2.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Button2.Location = new global::System.Drawing.Point(12, 300);
			this.Button2.Name = "Button2";
			this.Button2.Size = new global::System.Drawing.Size(52, 23);
			this.Button2.TabIndex = 28;
			this.Button2.Text = "Cancel";
			this.Button2.UseVisualStyleBackColor = true;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.White;
			base.ClientSize = new global::System.Drawing.Size(774, 329);
			base.ControlBox = false;
			base.Controls.Add(this.Button2);
			base.Controls.Add(this.Button1);
			base.Controls.Add(this.GroupBox1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Name = "frmCreateEditProfile";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Create/Edit Profile";
			base.TopMost = true;
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox11).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox10).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox9).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox8).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox7).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox6).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox5).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x04000066 RID: 102
		private global::System.ComponentModel.IContainer components;
	}
}
