namespace OculusTrayTool
{
	// Token: 0x02000058 RID: 88
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class FrmSetFallback : global::System.Windows.Forms.Form
	{
		// Token: 0x060008A2 RID: 2210 RVA: 0x0004FAC0 File Offset: 0x0004DCC0
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060008A3 RID: 2211 RVA: 0x0004FB10 File Offset: 0x0004DD10
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::OculusTrayTool.FrmSetFallback));
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.ComboBox3 = new global::System.Windows.Forms.ComboBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.ComboBox4 = new global::System.Windows.Forms.ComboBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.ComboBox5 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox6 = new global::System.Windows.Forms.ComboBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.ComboCommMicFallback = new global::System.Windows.Forms.ComboBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.ComboCommFallback = new global::System.Windows.Forms.ComboBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox2 = new global::System.Windows.Forms.ComboBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.ComboMicFallback = new global::System.Windows.Forms.ComboBox();
			this.ComboAudioFallback = new global::System.Windows.Forms.ComboBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.GroupBox1.SuspendLayout();
			base.SuspendLayout();
			this.GroupBox1.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.GroupBox1.Controls.Add(this.ComboBox3);
			this.GroupBox1.Controls.Add(this.Label8);
			this.GroupBox1.Controls.Add(this.ComboBox4);
			this.GroupBox1.Controls.Add(this.Label9);
			this.GroupBox1.Controls.Add(this.GroupBox4);
			this.GroupBox1.Controls.Add(this.GroupBox5);
			this.GroupBox1.Controls.Add(this.Label10);
			this.GroupBox1.Controls.Add(this.ComboBox5);
			this.GroupBox1.Controls.Add(this.ComboBox6);
			this.GroupBox1.Controls.Add(this.Label11);
			this.GroupBox1.Controls.Add(this.Label12);
			this.GroupBox1.Controls.Add(this.ComboCommMicFallback);
			this.GroupBox1.Controls.Add(this.Label7);
			this.GroupBox1.Controls.Add(this.ComboCommFallback);
			this.GroupBox1.Controls.Add(this.Label6);
			this.GroupBox1.Controls.Add(this.GroupBox3);
			this.GroupBox1.Controls.Add(this.GroupBox2);
			this.GroupBox1.Controls.Add(this.Label5);
			this.GroupBox1.Controls.Add(this.ComboBox1);
			this.GroupBox1.Controls.Add(this.ComboBox2);
			this.GroupBox1.Controls.Add(this.Label4);
			this.GroupBox1.Controls.Add(this.Label3);
			this.GroupBox1.Controls.Add(this.ComboMicFallback);
			this.GroupBox1.Controls.Add(this.ComboAudioFallback);
			this.GroupBox1.Controls.Add(this.Label2);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GroupBox1.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.GroupBox1.Location = new global::System.Drawing.Point(12, 12);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.Size = new global::System.Drawing.Size(409, 418);
			this.GroupBox1.TabIndex = 0;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Set when Audio/Mic devices should switch";
			this.ComboBox3.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.ComboBox3.BackColor = global::System.Drawing.Color.AliceBlue;
			this.ComboBox3.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboBox3.FormattingEnabled = true;
			this.ComboBox3.Location = new global::System.Drawing.Point(157, 224);
			this.ComboBox3.Name = "ComboBox3";
			this.ComboBox3.Size = new global::System.Drawing.Size(239, 23);
			this.ComboBox3.TabIndex = 29;
			this.Label8.AutoSize = true;
			this.Label8.Location = new global::System.Drawing.Point(23, 227);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(117, 15);
			this.Label8.TabIndex = 28;
			this.Label8.Text = "Mic Communication";
			this.ComboBox4.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.ComboBox4.BackColor = global::System.Drawing.Color.AliceBlue;
			this.ComboBox4.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboBox4.FormattingEnabled = true;
			this.ComboBox4.Location = new global::System.Drawing.Point(157, 195);
			this.ComboBox4.Name = "ComboBox4";
			this.ComboBox4.Size = new global::System.Drawing.Size(239, 23);
			this.ComboBox4.TabIndex = 27;
			this.Label9.AutoSize = true;
			this.Label9.Location = new global::System.Drawing.Point(23, 198);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(128, 15);
			this.Label9.TabIndex = 26;
			this.Label9.Text = "Audio Communication";
			this.GroupBox4.Location = new global::System.Drawing.Point(6, 111);
			this.GroupBox4.Name = "GroupBox4";
			this.GroupBox4.Size = new global::System.Drawing.Size(26, 10);
			this.GroupBox4.TabIndex = 25;
			this.GroupBox4.TabStop = false;
			this.GroupBox5.Location = new global::System.Drawing.Point(253, 113);
			this.GroupBox5.Name = "GroupBox5";
			this.GroupBox5.Size = new global::System.Drawing.Size(145, 10);
			this.GroupBox5.TabIndex = 24;
			this.GroupBox5.TabStop = false;
			this.Label10.AutoSize = true;
			this.Label10.Location = new global::System.Drawing.Point(38, 109);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(209, 15);
			this.Label10.TabIndex = 23;
			this.Label10.Text = "On Start/Load switch to these devices";
			this.ComboBox5.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.ComboBox5.BackColor = global::System.Drawing.Color.AliceBlue;
			this.ComboBox5.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboBox5.FormattingEnabled = true;
			this.ComboBox5.Location = new global::System.Drawing.Point(157, 166);
			this.ComboBox5.Name = "ComboBox5";
			this.ComboBox5.Size = new global::System.Drawing.Size(239, 23);
			this.ComboBox5.TabIndex = 22;
			this.ComboBox6.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.ComboBox6.BackColor = global::System.Drawing.Color.AliceBlue;
			this.ComboBox6.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboBox6.FormattingEnabled = true;
			this.ComboBox6.Location = new global::System.Drawing.Point(157, 137);
			this.ComboBox6.Name = "ComboBox6";
			this.ComboBox6.Size = new global::System.Drawing.Size(240, 23);
			this.ComboBox6.TabIndex = 21;
			this.Label11.AutoSize = true;
			this.Label11.Location = new global::System.Drawing.Point(23, 169);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(73, 15);
			this.Label11.TabIndex = 20;
			this.Label11.Text = "Microphone";
			this.Label12.AutoSize = true;
			this.Label12.Location = new global::System.Drawing.Point(26, 142);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(38, 15);
			this.Label12.TabIndex = 19;
			this.Label12.Text = "Audio";
			this.ComboCommMicFallback.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.ComboCommMicFallback.BackColor = global::System.Drawing.Color.AliceBlue;
			this.ComboCommMicFallback.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboCommMicFallback.FormattingEnabled = true;
			this.ComboCommMicFallback.Items.AddRange(new object[] { " " });
			this.ComboCommMicFallback.Location = new global::System.Drawing.Point(157, 375);
			this.ComboCommMicFallback.Name = "ComboCommMicFallback";
			this.ComboCommMicFallback.Size = new global::System.Drawing.Size(239, 23);
			this.ComboCommMicFallback.TabIndex = 18;
			this.Label7.AutoSize = true;
			this.Label7.Location = new global::System.Drawing.Point(23, 378);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(117, 15);
			this.Label7.TabIndex = 17;
			this.Label7.Text = "Mic Communication";
			this.ComboCommFallback.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.ComboCommFallback.BackColor = global::System.Drawing.Color.AliceBlue;
			this.ComboCommFallback.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboCommFallback.FormattingEnabled = true;
			this.ComboCommFallback.Location = new global::System.Drawing.Point(157, 346);
			this.ComboCommFallback.Name = "ComboCommFallback";
			this.ComboCommFallback.Size = new global::System.Drawing.Size(239, 23);
			this.ComboCommFallback.TabIndex = 16;
			this.Label6.AutoSize = true;
			this.Label6.Location = new global::System.Drawing.Point(23, 349);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(128, 15);
			this.Label6.TabIndex = 15;
			this.Label6.Text = "Audio Communication";
			this.GroupBox3.Location = new global::System.Drawing.Point(6, 262);
			this.GroupBox3.Name = "GroupBox3";
			this.GroupBox3.Size = new global::System.Drawing.Size(26, 10);
			this.GroupBox3.TabIndex = 14;
			this.GroupBox3.TabStop = false;
			this.GroupBox2.Location = new global::System.Drawing.Point(217, 264);
			this.GroupBox2.Name = "GroupBox2";
			this.GroupBox2.Size = new global::System.Drawing.Size(181, 10);
			this.GroupBox2.TabIndex = 13;
			this.GroupBox2.TabStop = false;
			this.Label5.AutoSize = true;
			this.Label5.Location = new global::System.Drawing.Point(38, 260);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(173, 15);
			this.Label5.TabIndex = 12;
			this.Label5.Text = "On Exit switch to these devices";
			this.ComboBox1.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.ComboBox1.BackColor = global::System.Drawing.Color.AliceBlue;
			this.ComboBox1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox1.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Items.AddRange(new object[] { "When Oculus Home starts/exits", "When Oculus Tray Tool starts/exits", "When a Profile loads/exits", "Never", "When SteamVR starts/exits" });
			this.ComboBox1.Location = new global::System.Drawing.Point(143, 34);
			this.ComboBox1.Name = "ComboBox1";
			this.ComboBox1.Size = new global::System.Drawing.Size(253, 23);
			this.ComboBox1.TabIndex = 8;
			this.ComboBox2.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.ComboBox2.BackColor = global::System.Drawing.Color.AliceBlue;
			this.ComboBox2.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox2.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboBox2.FormattingEnabled = true;
			this.ComboBox2.Items.AddRange(new object[] { "When Oculus Home starts/exits", "When Oculus Tray Tool starts/exits", "When a Profile loads/exits", "Never", "When SteamVR starts/exits" });
			this.ComboBox2.Location = new global::System.Drawing.Point(143, 63);
			this.ComboBox2.Name = "ComboBox2";
			this.ComboBox2.Size = new global::System.Drawing.Size(253, 23);
			this.ComboBox2.TabIndex = 9;
			this.Label4.AutoSize = true;
			this.Label4.Location = new global::System.Drawing.Point(23, 63);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(112, 15);
			this.Label4.TabIndex = 7;
			this.Label4.Text = "Switch Microphone";
			this.Label3.AutoSize = true;
			this.Label3.Location = new global::System.Drawing.Point(23, 34);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(77, 15);
			this.Label3.TabIndex = 6;
			this.Label3.Text = "Switch Audio";
			this.ComboMicFallback.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.ComboMicFallback.BackColor = global::System.Drawing.Color.AliceBlue;
			this.ComboMicFallback.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboMicFallback.FormattingEnabled = true;
			this.ComboMicFallback.Location = new global::System.Drawing.Point(157, 317);
			this.ComboMicFallback.Name = "ComboMicFallback";
			this.ComboMicFallback.Size = new global::System.Drawing.Size(239, 23);
			this.ComboMicFallback.TabIndex = 3;
			this.ComboAudioFallback.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.ComboAudioFallback.BackColor = global::System.Drawing.Color.AliceBlue;
			this.ComboAudioFallback.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboAudioFallback.FormattingEnabled = true;
			this.ComboAudioFallback.Location = new global::System.Drawing.Point(157, 288);
			this.ComboAudioFallback.Name = "ComboAudioFallback";
			this.ComboAudioFallback.Size = new global::System.Drawing.Size(240, 23);
			this.ComboAudioFallback.TabIndex = 2;
			this.Label2.AutoSize = true;
			this.Label2.Location = new global::System.Drawing.Point(23, 320);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(73, 15);
			this.Label2.TabIndex = 1;
			this.Label2.Text = "Microphone";
			this.Label1.AutoSize = true;
			this.Label1.Location = new global::System.Drawing.Point(26, 293);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(38, 15);
			this.Label1.TabIndex = 0;
			this.Label1.Text = "Audio";
			this.Button1.Anchor = global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button1.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Button1.Location = new global::System.Drawing.Point(366, 436);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(55, 25);
			this.Button1.TabIndex = 1;
			this.Button1.Text = "OK";
			this.Button1.UseVisualStyleBackColor = true;
			this.Button2.Anchor = global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left;
			this.Button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button2.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Button2.Location = new global::System.Drawing.Point(12, 436);
			this.Button2.Name = "Button2";
			this.Button2.Size = new global::System.Drawing.Size(55, 25);
			this.Button2.TabIndex = 2;
			this.Button2.Text = "Reset";
			this.Button2.UseVisualStyleBackColor = true;
			this.Button3.Anchor = global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right;
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button3.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Button3.Location = new global::System.Drawing.Point(306, 436);
			this.Button3.Name = "Button3";
			this.Button3.Size = new global::System.Drawing.Size(55, 25);
			this.Button3.TabIndex = 3;
			this.Button3.Text = "Cancel";
			this.Button3.UseVisualStyleBackColor = true;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(96f, 96f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Dpi;
			base.AutoSizeMode = global::System.Windows.Forms.AutoSizeMode.GrowAndShrink;
			this.BackColor = global::System.Drawing.Color.White;
			base.ClientSize = new global::System.Drawing.Size(433, 471);
			base.Controls.Add(this.Button3);
			base.Controls.Add(this.Button2);
			base.Controls.Add(this.Button1);
			base.Controls.Add(this.GroupBox1);
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			this.MinimumSize = new global::System.Drawing.Size(449, 510);
			base.Name = "FrmSetFallback";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Audio Swicher";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			base.ResumeLayout(false);
		}

		// Token: 0x040003AB RID: 939
		private global::System.ComponentModel.IContainer components;
	}
}
