namespace OculusTrayTool
{
	// Token: 0x02000060 RID: 96
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmVoiceSettings : global::System.Windows.Forms.Form
	{
		// Token: 0x0600093C RID: 2364 RVA: 0x00056398 File Offset: 0x00054598
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600093D RID: 2365 RVA: 0x000563E8 File Offset: 0x000545E8
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::OculusTrayTool.frmVoiceSettings));
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			this.Button3 = new global::System.Windows.Forms.Button();
			this.LabelConfidencePercent = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.TrackBar1 = new global::System.Windows.Forms.TrackBar();
			this.ImageList1 = new global::System.Windows.Forms.ImageList(this.components);
			this.DotNetBarTabcontrol1 = new global::OculusTrayTool.DotNetBarTabcontrol();
			this.TabPage3 = new global::System.Windows.Forms.TabPage();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.CheckBox7 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox5 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox6 = new global::System.Windows.Forms.CheckBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.LabelExplain = new global::System.Windows.Forms.Label();
			this.LabelKey = new global::System.Windows.Forms.Label();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.ButtonListen = new global::System.Windows.Forms.Button();
			this.CheckBox2 = new global::System.Windows.Forms.CheckBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.CheckBox3 = new global::System.Windows.Forms.CheckBox();
			this.ComboDevice = new global::System.Windows.Forms.ComboBox();
			this.CheckBox4 = new global::System.Windows.Forms.CheckBox();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.ListView1 = new global::System.Windows.Forms.ListView();
			this.ColumnHeader1 = new global::System.Windows.Forms.ColumnHeader();
			this.ColumnHeader2 = new global::System.Windows.Forms.ColumnHeader();
			this.ColumnHeader3 = new global::System.Windows.Forms.ColumnHeader();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.ListView2 = new global::System.Windows.Forms.ListView();
			this.ColumnHeader4 = new global::System.Windows.Forms.ColumnHeader();
			this.ColumnHeader5 = new global::System.Windows.Forms.ColumnHeader();
			this.GroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.TrackBar1).BeginInit();
			this.DotNetBarTabcontrol1.SuspendLayout();
			this.TabPage3.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.TabPage1.SuspendLayout();
			this.TabPage2.SuspendLayout();
			base.SuspendLayout();
			this.GroupBox1.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.GroupBox1.Controls.Add(this.Label2);
			this.GroupBox1.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.GroupBox1.Location = new global::System.Drawing.Point(12, 12);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.Size = new global::System.Drawing.Size(601, 47);
			this.GroupBox1.TabIndex = 0;
			this.GroupBox1.TabStop = false;
			this.Label2.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.Label2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label2.Location = new global::System.Drawing.Point(5, 10);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(585, 35);
			this.Label2.TabIndex = 0;
			this.Label2.Text = "Click on the Voice Command you want to edit and add/remove phrases to control that function. Commands are separated with a semicolon ( ; ).\r\n";
			this.Button1.Anchor = global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button1.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Button1.Location = new global::System.Drawing.Point(538, 474);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(75, 25);
			this.Button1.TabIndex = 5;
			this.Button1.Text = "OK";
			this.Button1.UseVisualStyleBackColor = true;
			this.Button3.Anchor = global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left;
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button3.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Button3.Location = new global::System.Drawing.Point(12, 474);
			this.Button3.Name = "Button3";
			this.Button3.Size = new global::System.Drawing.Size(83, 25);
			this.Button3.TabIndex = 10;
			this.Button3.Text = "Set Defaults";
			this.Button3.UseVisualStyleBackColor = true;
			this.LabelConfidencePercent.Anchor = global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left;
			this.LabelConfidencePercent.AutoSize = true;
			this.LabelConfidencePercent.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.LabelConfidencePercent.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.LabelConfidencePercent.Location = new global::System.Drawing.Point(308, 479);
			this.LabelConfidencePercent.Name = "LabelConfidencePercent";
			this.LabelConfidencePercent.Size = new global::System.Drawing.Size(0, 15);
			this.LabelConfidencePercent.TabIndex = 40;
			this.Label1.Anchor = global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left;
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label1.Location = new global::System.Drawing.Point(126, 479);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(72, 15);
			this.Label1.TabIndex = 39;
			this.Label1.Text = "Confidence:";
			this.TrackBar1.Anchor = global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left;
			this.TrackBar1.AutoSize = false;
			this.TrackBar1.Location = new global::System.Drawing.Point(201, 479);
			this.TrackBar1.Maximum = 100;
			this.TrackBar1.Minimum = 1;
			this.TrackBar1.Name = "TrackBar1";
			this.TrackBar1.Size = new global::System.Drawing.Size(107, 20);
			this.TrackBar1.TabIndex = 38;
			this.TrackBar1.TickStyle = global::System.Windows.Forms.TickStyle.None;
			this.TrackBar1.Value = 1;
			this.ImageList1.ImageStream = (global::System.Windows.Forms.ImageListStreamer)componentResourceManager.GetObject("ImageList1.ImageStream");
			this.ImageList1.TransparentColor = global::System.Drawing.Color.Transparent;
			this.ImageList1.Images.SetKeyName(0, "Very-Basic-Listen-icon.png");
			this.ImageList1.Images.SetKeyName(1, "Very-Basic-Not-Listen-icon.png");
			this.DotNetBarTabcontrol1.Alignment = global::System.Windows.Forms.TabAlignment.Left;
			this.DotNetBarTabcontrol1.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.DotNetBarTabcontrol1.Controls.Add(this.TabPage3);
			this.DotNetBarTabcontrol1.Controls.Add(this.TabPage1);
			this.DotNetBarTabcontrol1.Controls.Add(this.TabPage2);
			this.DotNetBarTabcontrol1.ItemSize = new global::System.Drawing.Size(43, 80);
			this.DotNetBarTabcontrol1.Location = new global::System.Drawing.Point(12, 65);
			this.DotNetBarTabcontrol1.Multiline = true;
			this.DotNetBarTabcontrol1.Name = "DotNetBarTabcontrol1";
			this.DotNetBarTabcontrol1.SelectedIndex = 0;
			this.DotNetBarTabcontrol1.Size = new global::System.Drawing.Size(601, 403);
			this.DotNetBarTabcontrol1.SizeMode = global::System.Windows.Forms.TabSizeMode.Fixed;
			this.DotNetBarTabcontrol1.TabIndex = 41;
			this.ToolTip1.SetToolTip(this.DotNetBarTabcontrol1, "Click to add command");
			this.TabPage3.BackColor = global::System.Drawing.Color.White;
			this.TabPage3.Controls.Add(this.GroupBox2);
			this.TabPage3.Location = new global::System.Drawing.Point(84, 4);
			this.TabPage3.Name = "TabPage3";
			this.TabPage3.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage3.Size = new global::System.Drawing.Size(513, 395);
			this.TabPage3.TabIndex = 2;
			this.TabPage3.Text = "Activation";
			this.GroupBox2.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.GroupBox2.Controls.Add(this.CheckBox7);
			this.GroupBox2.Controls.Add(this.CheckBox5);
			this.GroupBox2.Controls.Add(this.CheckBox6);
			this.GroupBox2.Controls.Add(this.Label3);
			this.GroupBox2.Controls.Add(this.LabelExplain);
			this.GroupBox2.Controls.Add(this.LabelKey);
			this.GroupBox2.Controls.Add(this.CheckBox1);
			this.GroupBox2.Controls.Add(this.ButtonListen);
			this.GroupBox2.Controls.Add(this.CheckBox2);
			this.GroupBox2.Controls.Add(this.Label4);
			this.GroupBox2.Controls.Add(this.CheckBox3);
			this.GroupBox2.Controls.Add(this.ComboDevice);
			this.GroupBox2.Controls.Add(this.CheckBox4);
			this.GroupBox2.Location = new global::System.Drawing.Point(6, 0);
			this.GroupBox2.Name = "GroupBox2";
			this.GroupBox2.Size = new global::System.Drawing.Size(501, 389);
			this.GroupBox2.TabIndex = 10;
			this.GroupBox2.TabStop = false;
			this.CheckBox7.Anchor = global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right;
			this.CheckBox7.AutoSize = true;
			this.CheckBox7.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.CheckBox7.Location = new global::System.Drawing.Point(355, 366);
			this.CheckBox7.Name = "CheckBox7";
			this.CheckBox7.Size = new global::System.Drawing.Size(138, 17);
			this.CheckBox7.TabIndex = 12;
			this.CheckBox7.Text = "Disable audio feedback";
			this.CheckBox7.UseVisualStyleBackColor = true;
			this.CheckBox5.AutoSize = true;
			this.CheckBox5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox5.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.CheckBox5.Location = new global::System.Drawing.Point(20, 162);
			this.CheckBox5.Name = "CheckBox5";
			this.CheckBox5.Size = new global::System.Drawing.Size(178, 19);
			this.CheckBox5.TabIndex = 10;
			this.CheckBox5.Text = "Joystick activated, continous";
			this.CheckBox5.UseVisualStyleBackColor = true;
			this.CheckBox6.AutoSize = true;
			this.CheckBox6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox6.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.CheckBox6.Location = new global::System.Drawing.Point(20, 187);
			this.CheckBox6.Name = "CheckBox6";
			this.CheckBox6.Size = new global::System.Drawing.Size(198, 19);
			this.CheckBox6.TabIndex = 11;
			this.CheckBox6.Text = "Joystick activated, Push-To-Talk";
			this.CheckBox6.UseVisualStyleBackColor = true;
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label3.Location = new global::System.Drawing.Point(6, 30);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(446, 15);
			this.Label3.TabIndex = 0;
			this.Label3.Text = "Select how voice commands should be enabled. You can select multiple options.";
			this.LabelExplain.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.LabelExplain.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.LabelExplain.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.LabelExplain.Location = new global::System.Drawing.Point(256, 70);
			this.LabelExplain.Name = "LabelExplain";
			this.LabelExplain.Size = new global::System.Drawing.Size(239, 178);
			this.LabelExplain.TabIndex = 2;
			this.LabelKey.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 15.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.LabelKey.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.LabelKey.Location = new global::System.Drawing.Point(19, 324);
			this.LabelKey.Name = "LabelKey";
			this.LabelKey.Size = new global::System.Drawing.Size(205, 25);
			this.LabelKey.TabIndex = 9;
			this.LabelKey.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.CheckBox1.AutoSize = true;
			this.CheckBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox1.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.CheckBox1.Location = new global::System.Drawing.Point(20, 70);
			this.CheckBox1.Name = "CheckBox1";
			this.CheckBox1.Size = new global::System.Drawing.Size(166, 19);
			this.CheckBox1.TabIndex = 1;
			this.CheckBox1.Text = "Voice activated, continous";
			this.CheckBox1.UseVisualStyleBackColor = true;
			this.ButtonListen.Enabled = false;
			this.ButtonListen.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.ButtonListen.Image = global::OculusTrayTool.My.Resources.Resources.Very_Basic_Not_Listen_icon;
			this.ButtonListen.Location = new global::System.Drawing.Point(242, 313);
			this.ButtonListen.Name = "ButtonListen";
			this.ButtonListen.Size = new global::System.Drawing.Size(56, 53);
			this.ButtonListen.TabIndex = 8;
			this.ToolTip1.SetToolTip(this.ButtonListen, "Click to capture button or key");
			this.ButtonListen.UseVisualStyleBackColor = true;
			this.CheckBox2.AutoSize = true;
			this.CheckBox2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox2.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.CheckBox2.Location = new global::System.Drawing.Point(20, 93);
			this.CheckBox2.Name = "CheckBox2";
			this.CheckBox2.Size = new global::System.Drawing.Size(162, 19);
			this.CheckBox2.TabIndex = 3;
			this.CheckBox2.Text = "Voice activated, repeated";
			this.CheckBox2.UseVisualStyleBackColor = true;
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label4.Location = new global::System.Drawing.Point(16, 247);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(208, 15);
			this.Label4.TabIndex = 7;
			this.Label4.Text = "Select device for button/key activation";
			this.CheckBox3.AutoSize = true;
			this.CheckBox3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox3.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.CheckBox3.Location = new global::System.Drawing.Point(20, 116);
			this.CheckBox3.Name = "CheckBox3";
			this.CheckBox3.Size = new global::System.Drawing.Size(188, 19);
			this.CheckBox3.TabIndex = 4;
			this.CheckBox3.Text = "Keyboard activated, continous";
			this.CheckBox3.UseVisualStyleBackColor = true;
			this.ComboDevice.Enabled = false;
			this.ComboDevice.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ComboDevice.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.ComboDevice.FormattingEnabled = true;
			this.ComboDevice.Location = new global::System.Drawing.Point(19, 265);
			this.ComboDevice.Name = "ComboDevice";
			this.ComboDevice.Size = new global::System.Drawing.Size(205, 23);
			this.ComboDevice.TabIndex = 6;
			this.CheckBox4.AutoSize = true;
			this.CheckBox4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox4.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.CheckBox4.Location = new global::System.Drawing.Point(20, 139);
			this.CheckBox4.Name = "CheckBox4";
			this.CheckBox4.Size = new global::System.Drawing.Size(208, 19);
			this.CheckBox4.TabIndex = 5;
			this.CheckBox4.Text = "Keyboard activated, Push-To-Talk";
			this.CheckBox4.UseVisualStyleBackColor = true;
			this.TabPage1.BackColor = global::System.Drawing.Color.White;
			this.TabPage1.Controls.Add(this.ListView1);
			this.TabPage1.Location = new global::System.Drawing.Point(84, 4);
			this.TabPage1.Name = "TabPage1";
			this.TabPage1.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage1.Size = new global::System.Drawing.Size(513, 395);
			this.TabPage1.TabIndex = 0;
			this.TabPage1.Text = "System";
			this.ListView1.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[] { this.ColumnHeader1, this.ColumnHeader2, this.ColumnHeader3 });
			this.ListView1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.ListView1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ListView1.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.ListView1.FullRowSelect = true;
			this.ListView1.GridLines = true;
			this.ListView1.Location = new global::System.Drawing.Point(3, 3);
			this.ListView1.Name = "ListView1";
			this.ListView1.Size = new global::System.Drawing.Size(507, 389);
			this.ListView1.TabIndex = 1;
			this.ListView1.UseCompatibleStateImageBehavior = false;
			this.ListView1.View = global::System.Windows.Forms.View.Details;
			this.ColumnHeader1.Text = "Action";
			this.ColumnHeader1.Width = 134;
			this.ColumnHeader2.Text = "Voice Command";
			this.ColumnHeader2.Width = 187;
			this.ColumnHeader3.Text = "Enabled";
			this.TabPage2.BackColor = global::System.Drawing.Color.White;
			this.TabPage2.Controls.Add(this.Button4);
			this.TabPage2.Controls.Add(this.Button2);
			this.TabPage2.Controls.Add(this.ComboBox1);
			this.TabPage2.Controls.Add(this.Label5);
			this.TabPage2.Controls.Add(this.ListView2);
			this.TabPage2.Location = new global::System.Drawing.Point(84, 4);
			this.TabPage2.Name = "TabPage2";
			this.TabPage2.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage2.Size = new global::System.Drawing.Size(513, 395);
			this.TabPage2.TabIndex = 1;
			this.TabPage2.Text = "User";
			this.Button4.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button4.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Button4.Location = new global::System.Drawing.Point(299, 7);
			this.Button4.Name = "Button4";
			this.Button4.Size = new global::System.Drawing.Size(75, 23);
			this.Button4.TabIndex = 4;
			this.Button4.Text = "Add Profile";
			this.Button4.UseVisualStyleBackColor = true;
			this.Button2.Enabled = false;
			this.Button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button2.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Button2.Location = new global::System.Drawing.Point(218, 7);
			this.Button2.Name = "Button2";
			this.Button2.Size = new global::System.Drawing.Size(75, 23);
			this.Button2.TabIndex = 3;
			this.Button2.Text = "Edit Profile";
			this.Button2.UseVisualStyleBackColor = true;
			this.ComboBox1.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Location = new global::System.Drawing.Point(48, 9);
			this.ComboBox1.Name = "ComboBox1";
			this.ComboBox1.Size = new global::System.Drawing.Size(164, 21);
			this.ComboBox1.TabIndex = 2;
			this.Label5.AutoSize = true;
			this.Label5.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.Label5.Location = new global::System.Drawing.Point(6, 12);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(36, 13);
			this.Label5.TabIndex = 1;
			this.Label5.Text = "Profile";
			this.ListView2.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.ListView2.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[] { this.ColumnHeader4, this.ColumnHeader5 });
			this.ListView2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ListView2.ForeColor = global::System.Drawing.Color.DodgerBlue;
			this.ListView2.FullRowSelect = true;
			this.ListView2.GridLines = true;
			this.ListView2.Location = new global::System.Drawing.Point(3, 38);
			this.ListView2.Name = "ListView2";
			this.ListView2.Size = new global::System.Drawing.Size(507, 354);
			this.ListView2.TabIndex = 0;
			this.ListView2.UseCompatibleStateImageBehavior = false;
			this.ListView2.View = global::System.Windows.Forms.View.Details;
			this.ColumnHeader4.Text = "Spoken Command";
			this.ColumnHeader4.Width = 264;
			this.ColumnHeader5.Text = "Actions";
			this.ColumnHeader5.Width = 227;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.AutoSizeMode = global::System.Windows.Forms.AutoSizeMode.GrowAndShrink;
			this.BackColor = global::System.Drawing.Color.White;
			base.ClientSize = new global::System.Drawing.Size(625, 508);
			base.Controls.Add(this.DotNetBarTabcontrol1);
			base.Controls.Add(this.LabelConfidencePercent);
			base.Controls.Add(this.Label1);
			base.Controls.Add(this.TrackBar1);
			base.Controls.Add(this.Button3);
			base.Controls.Add(this.Button1);
			base.Controls.Add(this.GroupBox1);
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.KeyPreview = true;
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "frmVoiceSettings";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Configure Voice Commands";
			this.GroupBox1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.TrackBar1).EndInit();
			this.DotNetBarTabcontrol1.ResumeLayout(false);
			this.TabPage3.ResumeLayout(false);
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.TabPage1.ResumeLayout(false);
			this.TabPage2.ResumeLayout(false);
			this.TabPage2.PerformLayout();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x040003EC RID: 1004
		private global::System.ComponentModel.IContainer components;
	}
}
