using OculusTrayTool.MyNameSpace;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using System.Management;

namespace OculusTrayTool
{
    partial class frmProfiles
    {
        private System.ComponentModel.IContainer components = null;

protected override void Dispose(bool disposing)
    {
      try
      {
        if (!disposing || this.components == null)
          return;
        this.components.Dispose();
      }
      finally
      {
        base.Dispose(disposing);
      }
    }

        #region Windows Form Designer generated code

    private void InitializeComponent()
    {
      this.components = (IContainer) new System.ComponentModel.Container();
      System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof (frmProfiles));
      this.ListView1 = new ListView();
      this.ColumnHeader1 = new ColumnHeader();
      this.ColumnHeader2 = new ColumnHeader();
      this.ColumnHeader3 = new ColumnHeader();
      this.ColumnHeader4 = new ColumnHeader();
      this.ColumnHeader5 = new ColumnHeader();
      this.ContextMenuStrip1 = new ContextMenuStrip(this.components);
      this.ToolStripMenuItem1 = new ToolStripMenuItem();
      this.ToolStripMenuItem2 = new ToolStripMenuItem();
      this.ToolStripSeparator1 = new ToolStripSeparator();
      this.LaunchAppToolStripMenuItem = new ToolStripMenuItem();
      this.LaunchAppWithOptionsToolStripMenuItem = new ToolStripMenuItem();
      this.ToolStripSeparator2 = new ToolStripSeparator();
      this.ToolStripMenuItem3 = new ToolStripMenuItem();
      this.ToolStripMenuItem4 = new ToolStripMenuItem();
      this.ToolStripMenuItem6 = new ToolStripMenuItem();
      this.ToolStripSeparator3 = new ToolStripSeparator();
      this.ToolStripMenuItem5 = new ToolStripMenuItem();
      this.RemoveAllSelectedProfilesToolStripMenuItem = new ToolStripMenuItem();
      this.Button2 = new Button();
      this.ToolTip1 = new ToolTip(this.components);
      this.GroupBox2 = new GroupBox();
      this.Label2 = new Label();
      this.CheckVoiceConfirm = new CheckBox();
      this.Button1 = new Button();
      this.Label1 = new Label();
      this.ComboResolution = new ComboBox();
      this.Button3 = new Button();
      this.DbLayoutPanel1 = new DBLayoutPanel(this.components);
      this.Label3 = new Label();
      this.Label4 = new Label();
      this.Label5 = new Label();
      this.Label16 = new Label();
      this.Label17 = new Label();
      this.Label18 = new Label();
      this.Label19 = new Label();
      this.Label20 = new Label();
      this.Label22 = new Label();
      this.Label23 = new Label();
      this.Label24 = new Label();
      this.Label25 = new Label();
      this.Label26 = new Label();
      this.Label27 = new Label();
      this.Label28 = new Label();
      this.Label30 = new Label();
      this.Label29 = new Label();
      this.Label15 = new Label();
      this.Label14 = new Label();
      this.Label13 = new Label();
      this.Label12 = new Label();
      this.Label11 = new Label();
      this.Label10 = new Label();
      this.Label9 = new Label();
      this.Label8 = new Label();
      this.Label7 = new Label();
      this.Label6 = new Label();
      this.Label31 = new Label();
      this.Label32 = new Label();
      this.TextBox1 = new TextBox();
      this.ContextMenuStrip1.SuspendLayout();
      this.GroupBox2.SuspendLayout();
      this.DbLayoutPanel1.SuspendLayout();
      this.SuspendLayout();
      this.ListView1.CheckBoxes = true;
      this.ListView1.Columns.AddRange(new ColumnHeader[5]
      {
        this.ColumnHeader1,
        this.ColumnHeader2,
        this.ColumnHeader3,
        this.ColumnHeader4,
        this.ColumnHeader5
      });
      this.ListView1.ContextMenuStrip = this.ContextMenuStrip1;
      this.ListView1.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.ListView1.ForeColor = Color.DodgerBlue;
      this.ListView1.FullRowSelect = true;
      this.ListView1.GridLines = true;
      this.ListView1.HeaderStyle = ColumnHeaderStyle.Nonclickable;
      this.ListView1.HideSelection = false;
      this.ListView1.Location = new Point(13, 128);
      this.ListView1.MultiSelect = false;
      this.ListView1.Name = "ListView1";
      this.ListView1.OwnerDraw = true;
      this.ListView1.Size = new Size(507, 379);
      this.ListView1.TabIndex = 1;
      this.ListView1.UseCompatibleStateImageBehavior = false;
      this.ListView1.View = View.Details;
      this.ColumnHeader1.Text = "   Game Name";
      this.ColumnHeader1.Width = 116;
      this.ColumnHeader2.Text = "Super Sampling";
      this.ColumnHeader2.Width = 164;
      this.ColumnHeader3.Text = "ASW Mode";
      this.ColumnHeader3.Width = 110;
      this.ColumnHeader4.Text = "CPU Priority";
      this.ColumnHeader4.Width = 113;
      this.ColumnHeader5.Text = "Enabled";
      this.ContextMenuStrip1.Items.AddRange(new ToolStripItem[12]
      {
        (ToolStripItem) this.ToolStripMenuItem1,
        (ToolStripItem) this.ToolStripMenuItem2,
        (ToolStripItem) this.ToolStripSeparator1,
        (ToolStripItem) this.LaunchAppToolStripMenuItem,
        (ToolStripItem) this.LaunchAppWithOptionsToolStripMenuItem,
        (ToolStripItem) this.ToolStripSeparator2,
        (ToolStripItem) this.ToolStripMenuItem3,
        (ToolStripItem) this.ToolStripMenuItem4,
        (ToolStripItem) this.ToolStripMenuItem6,
        (ToolStripItem) this.ToolStripSeparator3,
        (ToolStripItem) this.ToolStripMenuItem5,
        (ToolStripItem) this.RemoveAllSelectedProfilesToolStripMenuItem
      });
      this.ContextMenuStrip1.Name = "ContextMenuStrip1";
      this.ContextMenuStrip1.Size = new Size(242, 220);
      this.ToolStripMenuItem1.Name = "ToolStripMenuItem1";
      this.ToolStripMenuItem1.Size = new Size(241, 22);
      this.ToolStripMenuItem1.Text = "Hide App in Profiles";
      this.ToolStripMenuItem1.Visible = false;
      this.ToolStripMenuItem2.Name = "ToolStripMenuItem2";
      this.ToolStripMenuItem2.Size = new Size(241, 22);
      this.ToolStripMenuItem2.Text = "Hide App in Profiles and Library";
      this.ToolStripMenuItem2.Visible = false;
      this.ToolStripSeparator1.Name = "ToolStripSeparator1";
      this.ToolStripSeparator1.Size = new Size(238, 6);
      this.LaunchAppToolStripMenuItem.Image = (Image) (System.Drawing.Image)OculusTrayTool.My.Resources.Resources.Service_Start;
      this.LaunchAppToolStripMenuItem.Name = "LaunchAppToolStripMenuItem";
      this.LaunchAppToolStripMenuItem.Size = new Size(241, 22);
      this.LaunchAppToolStripMenuItem.Text = "Launch App";
      this.LaunchAppWithOptionsToolStripMenuItem.Name = "LaunchAppWithOptionsToolStripMenuItem";
      this.LaunchAppWithOptionsToolStripMenuItem.Size = new Size(241, 22);
      this.LaunchAppWithOptionsToolStripMenuItem.Text = "Launch App with options..";
      this.ToolStripSeparator2.Name = "ToolStripSeparator2";
      this.ToolStripSeparator2.Size = new Size(238, 6);
      this.ToolStripMenuItem3.Image = (Image) (System.Drawing.Image)OculusTrayTool.My.Resources.Resources.Icon_Edit;
      this.ToolStripMenuItem3.Name = "ToolStripMenuItem3";
      this.ToolStripMenuItem3.Size = new Size(241, 22);
      this.ToolStripMenuItem3.Text = "Create New Profile...";
      this.ToolStripMenuItem4.Image = (Image) (System.Drawing.Image)OculusTrayTool.My.Resources.Resources.Icon_Edit;
      this.ToolStripMenuItem4.Name = "ToolStripMenuItem4";
      this.ToolStripMenuItem4.Size = new Size(241, 22);
      this.ToolStripMenuItem4.Text = "Edit highlighted profile...";
      this.ToolStripMenuItem6.Image = (Image) (System.Drawing.Image)OculusTrayTool.My.Resources.Resources.Icon_Edit;
      this.ToolStripMenuItem6.Name = "ToolStripMenuItem6";
      this.ToolStripMenuItem6.Size = new Size(241, 22);
      this.ToolStripMenuItem6.Text = "Edit all selected...";
      this.ToolStripSeparator3.Name = "ToolStripSeparator3";
      this.ToolStripSeparator3.Size = new Size(238, 6);
      this.ToolStripMenuItem5.Image = (Image) (System.Drawing.Image)OculusTrayTool.My.Resources.Resources.Icon_Delete;
      this.ToolStripMenuItem5.Name = "ToolStripMenuItem5";
      this.ToolStripMenuItem5.Size = new Size(241, 22);
      this.ToolStripMenuItem5.Text = "Remove highlighted Profile";
      this.RemoveAllSelectedProfilesToolStripMenuItem.Image = (Image) (System.Drawing.Image)OculusTrayTool.My.Resources.Resources.Icon_Delete;
      this.RemoveAllSelectedProfilesToolStripMenuItem.Name = "RemoveAllSelectedProfilesToolStripMenuItem";
      this.RemoveAllSelectedProfilesToolStripMenuItem.Size = new Size(241, 22);
      this.RemoveAllSelectedProfilesToolStripMenuItem.Text = "Remove all selected Profiles";
      this.RemoveAllSelectedProfilesToolStripMenuItem.Visible = false;
      this.Button2.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
      this.Button2.FlatStyle = FlatStyle.Flat;
      this.Button2.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Button2.ForeColor = Color.DodgerBlue;
      this.Button2.Location = new Point(856, 542);
      this.Button2.Name = "Button2";
      this.Button2.Size = new Size(62, 25);
      this.Button2.TabIndex = 3;
      this.Button2.Text = "Close";
      this.Button2.UseVisualStyleBackColor = true;
      this.GroupBox2.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.GroupBox2.Controls.Add(this.Label2);
      this.GroupBox2.ForeColor = Color.DodgerBlue;
      this.GroupBox2.Location = new Point(12, 12);
      this.GroupBox2.Name = "GroupBox2";
      this.GroupBox2.Size = new Size(905, 79);
      this.GroupBox2.TabIndex = 10;
      this.GroupBox2.TabStop = false;
      this.Label2.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.Label2.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Label2.Location = new Point(12, 13);
      this.Label2.Name = "Label2";
      this.Label2.Size = new Size(887, 60);
      this.Label2.TabIndex = 0;
      this.Label2.Text = "Double-click to edit, right-click for options.\r\n\r\nTip: You can select multiple profiles and use \"Edit all selected\" to change settings for all of them at once.\r\n";
      this.CheckVoiceConfirm.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.CheckVoiceConfirm.AutoSize = true;
      this.CheckVoiceConfirm.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.CheckVoiceConfirm.ForeColor = Color.DodgerBlue;
      this.CheckVoiceConfirm.Location = new Point(12, 513);
      this.CheckVoiceConfirm.Name = "CheckVoiceConfirm";
      this.CheckVoiceConfirm.Size = new Size(254, 19);
      this.CheckVoiceConfirm.TabIndex = 15;
      this.CheckVoiceConfirm.Text = "Audio confirmation when profile is applied";
      this.CheckVoiceConfirm.UseVisualStyleBackColor = true;
      this.Button1.FlatStyle = FlatStyle.Flat;
      this.Button1.ForeColor = Color.DodgerBlue;
      this.Button1.Location = new Point(12, 97);
      this.Button1.Name = "Button1";
      this.Button1.Size = new Size(92, 25);
      this.Button1.TabIndex = 25;
      this.Button1.Text = "Create profile";
      this.Button1.UseVisualStyleBackColor = true;
      this.Label1.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.Label1.AutoSize = true;
      this.Label1.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Label1.ForeColor = Color.DodgerBlue;
      this.Label1.Location = new Point(10, 542);
      this.Label1.Name = "Label1";
      this.Label1.Size = new Size(112, 15);
      this.Label1.TabIndex = 26;
      this.Label1.Text = "Desktop resolution:";
      this.ComboResolution.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.ComboResolution.FormattingEnabled = true;
      this.ComboResolution.Location = new Point(125, 541);
      this.ComboResolution.Name = "ComboResolution";
      this.ComboResolution.Size = new Size(104, 21);
      this.ComboResolution.TabIndex = 27;
      this.Button3.Enabled = false;
      this.Button3.FlatStyle = FlatStyle.Flat;
      this.Button3.ForeColor = Color.DodgerBlue;
      this.Button3.Location = new Point(110, 97);
      this.Button3.Name = "Button3";
      this.Button3.Size = new Size(71, 25);
      this.Button3.TabIndex = 29;
      this.Button3.Text = "Edit profile";
      this.Button3.UseVisualStyleBackColor = true;
      this.DbLayoutPanel1.CellBorderStyle = TableLayoutPanelCellBorderStyle.Single;
      this.DbLayoutPanel1.ColumnCount = 2;
      this.DbLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 41.14583f));
      this.DbLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58.85417f));
      this.DbLayoutPanel1.Controls.Add(this.Label3, 0, 0);
      this.DbLayoutPanel1.Controls.Add(this.Label4, 0, 1);
      this.DbLayoutPanel1.Controls.Add(this.Label5, 0, 2);
      this.DbLayoutPanel1.Controls.Add(this.Label16, 1, 0);
      this.DbLayoutPanel1.Controls.Add(this.Label17, 1, 1);
      this.DbLayoutPanel1.Controls.Add(this.Label18, 1, 2);
      this.DbLayoutPanel1.Controls.Add(this.Label19, 1, 3);
      this.DbLayoutPanel1.Controls.Add(this.Label20, 1, 4);
      this.DbLayoutPanel1.Controls.Add(this.Label22, 1, 6);
      this.DbLayoutPanel1.Controls.Add(this.Label23, 1, 7);
      this.DbLayoutPanel1.Controls.Add(this.Label24, 1, 8);
      this.DbLayoutPanel1.Controls.Add(this.Label25, 1, 9);
      this.DbLayoutPanel1.Controls.Add(this.Label26, 1, 10);
      this.DbLayoutPanel1.Controls.Add(this.Label27, 1, 11);
      this.DbLayoutPanel1.Controls.Add(this.Label28, 1, 12);
      this.DbLayoutPanel1.Controls.Add(this.Label30, 1, 13);
      this.DbLayoutPanel1.Controls.Add(this.Label29, 0, 14);
      this.DbLayoutPanel1.Controls.Add(this.Label15, 0, 13);
      this.DbLayoutPanel1.Controls.Add(this.Label14, 0, 12);
      this.DbLayoutPanel1.Controls.Add(this.Label13, 0, 11);
      this.DbLayoutPanel1.Controls.Add(this.Label12, 0, 10);
      this.DbLayoutPanel1.Controls.Add(this.Label11, 0, 9);
      this.DbLayoutPanel1.Controls.Add(this.Label10, 0, 8);
      this.DbLayoutPanel1.Controls.Add(this.Label9, 0, 7);
      this.DbLayoutPanel1.Controls.Add(this.Label8, 0, 6);
      this.DbLayoutPanel1.Controls.Add(this.Label7, 0, 5);
      this.DbLayoutPanel1.Controls.Add(this.Label6, 0, 4);
      this.DbLayoutPanel1.Controls.Add(this.Label31, 1, 14);
      this.DbLayoutPanel1.Controls.Add(this.Label32, 0, 3);
      this.DbLayoutPanel1.Controls.Add(this.TextBox1, 1, 5);
      this.DbLayoutPanel1.ForeColor = Color.DodgerBlue;
      this.DbLayoutPanel1.Location = new Point(526, 128);
      this.DbLayoutPanel1.Name = "DbLayoutPanel1";
      this.DbLayoutPanel1.RowCount = 15;
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.845564f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.297919f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 6.681271f));
      this.DbLayoutPanel1.Size = new Size(391, 379);
      this.DbLayoutPanel1.TabIndex = 0;
      this.Label3.AutoSize = true;
      this.Label3.Dock = DockStyle.Fill;
      this.Label3.Location = new Point(4, 1);
      this.Label3.Name = "Label3";
      this.Label3.Size = new Size(153, 24);
      this.Label3.TabIndex = 0;
      this.Label3.Text = "Game name";
      this.Label3.TextAlign = ContentAlignment.MiddleLeft;
      this.Label4.AutoSize = true;
      this.Label4.Dock = DockStyle.Fill;
      this.Label4.Location = new Point(4, 26);
      this.Label4.Name = "Label4";
      this.Label4.Size = new Size(153, 24);
      this.Label4.TabIndex = 1;
      this.Label4.Text = "Super Sampling";
      this.Label4.TextAlign = ContentAlignment.MiddleLeft;
      this.Label5.AutoSize = true;
      this.Label5.Dock = DockStyle.Fill;
      this.Label5.Location = new Point(4, 51);
      this.Label5.Name = "Label5";
      this.Label5.Size = new Size(153, 24);
      this.Label5.TabIndex = 2;
      this.Label5.Text = "ASW Mode";
      this.Label5.TextAlign = ContentAlignment.MiddleLeft;
      this.Label16.AutoSize = true;
      this.Label16.Dock = DockStyle.Fill;
      this.Label16.Location = new Point(164, 1);
      this.Label16.Name = "Label16";
      this.Label16.Size = new Size(223, 24);
      this.Label16.TabIndex = 13;
      this.Label16.Text = "Label16";
      this.Label16.TextAlign = ContentAlignment.MiddleLeft;
      this.Label16.Visible = false;
      this.Label17.AutoSize = true;
      this.Label17.Dock = DockStyle.Fill;
      this.Label17.Location = new Point(164, 26);
      this.Label17.Name = "Label17";
      this.Label17.Size = new Size(223, 24);
      this.Label17.TabIndex = 14;
      this.Label17.Text = "Label17";
      this.Label17.TextAlign = ContentAlignment.MiddleLeft;
      this.Label17.Visible = false;
      this.Label18.AutoSize = true;
      this.Label18.Dock = DockStyle.Fill;
      this.Label18.Location = new Point(164, 51);
      this.Label18.Name = "Label18";
      this.Label18.Size = new Size(223, 24);
      this.Label18.TabIndex = 15;
      this.Label18.Text = "Label18";
      this.Label18.TextAlign = ContentAlignment.MiddleLeft;
      this.Label18.Visible = false;
      this.Label19.AutoSize = true;
      this.Label19.Dock = DockStyle.Fill;
      this.Label19.Location = new Point(164, 76);
      this.Label19.Name = "Label19";
      this.Label19.Size = new Size(223, 24);
      this.Label19.TabIndex = 16;
      this.Label19.Text = "Label19";
      this.Label19.TextAlign = ContentAlignment.MiddleLeft;
      this.Label19.Visible = false;
      this.Label20.AutoSize = true;
      this.Label20.Dock = DockStyle.Fill;
      this.Label20.Location = new Point(164, 101);
      this.Label20.Name = "Label20";
      this.Label20.Size = new Size(223, 24);
      this.Label20.TabIndex = 17;
      this.Label20.Text = "Label20";
      this.Label20.TextAlign = ContentAlignment.MiddleLeft;
      this.Label20.Visible = false;
      this.Label22.AutoSize = true;
      this.Label22.Dock = DockStyle.Fill;
      this.Label22.Location = new Point(164, 151);
      this.Label22.Name = "Label22";
      this.Label22.Size = new Size(223, 24);
      this.Label22.TabIndex = 19;
      this.Label22.Text = "Label22";
      this.Label22.TextAlign = ContentAlignment.MiddleLeft;
      this.Label22.Visible = false;
      this.Label23.AutoSize = true;
      this.Label23.Dock = DockStyle.Fill;
      this.Label23.Location = new Point(164, 176);
      this.Label23.Name = "Label23";
      this.Label23.Size = new Size(223, 24);
      this.Label23.TabIndex = 20;
      this.Label23.Text = "Label23";
      this.Label23.TextAlign = ContentAlignment.MiddleLeft;
      this.Label23.Visible = false;
      this.Label24.AutoSize = true;
      this.Label24.Dock = DockStyle.Fill;
      this.Label24.Location = new Point(164, 201);
      this.Label24.Name = "Label24";
      this.Label24.Size = new Size(223, 24);
      this.Label24.TabIndex = 21;
      this.Label24.Text = "Label24";
      this.Label24.TextAlign = ContentAlignment.MiddleLeft;
      this.Label24.Visible = false;
      this.Label25.AutoSize = true;
      this.Label25.Dock = DockStyle.Fill;
      this.Label25.Location = new Point(164, 226);
      this.Label25.Name = "Label25";
      this.Label25.Size = new Size(223, 24);
      this.Label25.TabIndex = 22;
      this.Label25.Text = "Label25";
      this.Label25.TextAlign = ContentAlignment.MiddleLeft;
      this.Label25.Visible = false;
      this.Label26.AutoSize = true;
      this.Label26.Dock = DockStyle.Fill;
      this.Label26.Location = new Point(164, 251);
      this.Label26.Name = "Label26";
      this.Label26.Size = new Size(223, 24);
      this.Label26.TabIndex = 23;
      this.Label26.Text = "Label26";
      this.Label26.TextAlign = ContentAlignment.MiddleLeft;
      this.Label26.Visible = false;
      this.Label27.AutoSize = true;
      this.Label27.Dock = DockStyle.Fill;
      this.Label27.Location = new Point(164, 276);
      this.Label27.Name = "Label27";
      this.Label27.Size = new Size(223, 24);
      this.Label27.TabIndex = 24;
      this.Label27.Text = "Label27";
      this.Label27.TextAlign = ContentAlignment.MiddleLeft;
      this.Label27.Visible = false;
      this.Label28.AutoSize = true;
      this.Label28.Dock = DockStyle.Fill;
      this.Label28.Location = new Point(164, 301);
      this.Label28.Name = "Label28";
      this.Label28.Size = new Size(223, 22);
      this.Label28.TabIndex = 25;
      this.Label28.Text = "Label28";
      this.Label28.TextAlign = ContentAlignment.MiddleLeft;
      this.Label28.Visible = false;
      this.Label30.AutoSize = true;
      this.Label30.Dock = DockStyle.Fill;
      this.Label30.Location = new Point(164, 324);
      this.Label30.Name = "Label30";
      this.Label30.Size = new Size(223, 24);
      this.Label30.TabIndex = 27;
      this.Label30.Text = "Label30";
      this.Label30.TextAlign = ContentAlignment.MiddleLeft;
      this.Label30.Visible = false;
      this.Label29.AutoSize = true;
      this.Label29.Dock = DockStyle.Fill;
      this.Label29.Location = new Point(4, 349);
      this.Label29.Name = "Label29";
      this.Label29.Size = new Size(153, 29);
      this.Label29.TabIndex = 26;
      this.Label29.Text = "Enabled";
      this.Label29.TextAlign = ContentAlignment.MiddleLeft;
      this.Label15.AutoSize = true;
      this.Label15.Dock = DockStyle.Fill;
      this.Label15.Location = new Point(4, 324);
      this.Label15.Name = "Label15";
      this.Label15.Size = new Size(153, 24);
      this.Label15.TabIndex = 12;
      this.Label15.Text = "Offset MipMap Bias";
      this.Label15.TextAlign = ContentAlignment.MiddleLeft;
      this.Label14.AutoSize = true;
      this.Label14.Dock = DockStyle.Fill;
      this.Label14.Location = new Point(4, 301);
      this.Label14.Name = "Label14";
      this.Label14.Size = new Size(153, 22);
      this.Label14.TabIndex = 11;
      this.Label14.Text = "Force MipMap Generation";
      this.Label14.TextAlign = ContentAlignment.MiddleLeft;
      this.Label13.AutoSize = true;
      this.Label13.Dock = DockStyle.Fill;
      this.Label13.Location = new Point(4, 276);
      this.Label13.Name = "Label13";
      this.Label13.Size = new Size(153, 24);
      this.Label13.TabIndex = 10;
      this.Label13.Text = "FoV";
      this.Label13.TextAlign = ContentAlignment.MiddleLeft;
      this.Label12.AutoSize = true;
      this.Label12.Dock = DockStyle.Fill;
      this.Label12.Location = new Point(4, 251);
      this.Label12.Name = "Label12";
      this.Label12.Size = new Size(153, 24);
      this.Label12.TabIndex = 9;
      this.Label12.Text = "Comment";
      this.Label12.TextAlign = ContentAlignment.MiddleLeft;
      this.Label11.AutoSize = true;
      this.Label11.Dock = DockStyle.Fill;
      this.Label11.Location = new Point(4, 226);
      this.Label11.Name = "Label11";
      this.Label11.Size = new Size(153, 24);
      this.Label11.TabIndex = 8;
      this.Label11.Text = "Adaptive GPU";
      this.Label11.TextAlign = ContentAlignment.MiddleLeft;
      this.Label10.AutoSize = true;
      this.Label10.Dock = DockStyle.Fill;
      this.Label10.Location = new Point(4, 201);
      this.Label10.Name = "Label10";
      this.Label10.Size = new Size(153, 24);
      this.Label10.TabIndex = 7;
      this.Label10.Text = "Mirror";
      this.Label10.TextAlign = ContentAlignment.MiddleLeft;
      this.Label9.AutoSize = true;
      this.Label9.Dock = DockStyle.Fill;
      this.Label9.Location = new Point(4, 176);
      this.Label9.Name = "Label9";
      this.Label9.Size = new Size(153, 24);
      this.Label9.TabIndex = 6;
      this.Label9.Text = "CPU Delay";
      this.Label9.TextAlign = ContentAlignment.MiddleLeft;
      this.Label8.AutoSize = true;
      this.Label8.Dock = DockStyle.Fill;
      this.Label8.Location = new Point(4, 151);
      this.Label8.Name = "Label8";
      this.Label8.Size = new Size(153, 24);
      this.Label8.TabIndex = 5;
      this.Label8.Text = "ASW Delay";
      this.Label8.TextAlign = ContentAlignment.MiddleLeft;
      this.Label7.AutoSize = true;
      this.Label7.Dock = DockStyle.Fill;
      this.Label7.Location = new Point(4, 126);
      this.Label7.Name = "Label7";
      this.Label7.Size = new Size(153, 24);
      this.Label7.TabIndex = 4;
      this.Label7.Text = "Path";
      this.Label7.TextAlign = ContentAlignment.MiddleLeft;
      this.Label6.AutoSize = true;
      this.Label6.Dock = DockStyle.Fill;
      this.Label6.Location = new Point(4, 101);
      this.Label6.Name = "Label6";
      this.Label6.Size = new Size(153, 24);
      this.Label6.TabIndex = 3;
      this.Label6.Text = "CPU Priority";
      this.Label6.TextAlign = ContentAlignment.MiddleLeft;
      this.Label31.AutoSize = true;
      this.Label31.Dock = DockStyle.Fill;
      this.Label31.Location = new Point(164, 349);
      this.Label31.Name = "Label31";
      this.Label31.Size = new Size(223, 29);
      this.Label31.TabIndex = 28;
      this.Label31.Text = "Label31";
      this.Label31.TextAlign = ContentAlignment.MiddleLeft;
      this.Label31.Visible = false;
      this.Label32.AutoSize = true;
      this.Label32.Dock = DockStyle.Fill;
      this.Label32.Location = new Point(4, 76);
      this.Label32.Name = "Label32";
      this.Label32.Size = new Size(153, 24);
      this.Label32.TabIndex = 29;
      this.Label32.Text = "Detection Method";
      this.Label32.TextAlign = ContentAlignment.MiddleLeft;
      this.TextBox1.BorderStyle = BorderStyle.None;
      this.TextBox1.Dock = DockStyle.Fill;
      this.TextBox1.ForeColor = Color.DodgerBlue;
      this.TextBox1.Location = new Point(164, 129);
      this.TextBox1.Name = "TextBox1";
      this.TextBox1.Size = new Size(223, 13);
      this.TextBox1.TabIndex = 30;
      this.TextBox1.Visible = false;
      this.AutoScaleDimensions = new SizeF(96f, 96f);
      this.AutoScaleMode = AutoScaleMode.Dpi;
      this.AutoSizeMode = AutoSizeMode.GrowAndShrink;
      this.BackColor = Color.White;
      this.ClientSize = new Size(930, 574);
      this.Controls.Add(this.DbLayoutPanel1);
      this.Controls.Add(this.Button3);
      this.Controls.Add(this.ComboResolution);
      this.Controls.Add(this.Label1);
      this.Controls.Add(this.Button1);
      this.Controls.Add(this.CheckVoiceConfirm);
      this.Controls.Add(this.GroupBox2);
      this.Controls.Add(this.Button2);
      this.Controls.Add(this.ListView1);
      this.FormBorderStyle = FormBorderStyle.FixedSingle;
      this.Icon = (Icon) resources.GetObject("$this.Icon");
      this.KeyPreview = true;
      this.MinimumSize = new Size(946, 613);
      this.Name = "frmProfiles";
      this.ShowIcon = false;
      this.SizeGripStyle = SizeGripStyle.Show;
      this.StartPosition = FormStartPosition.CenterScreen;
      this.Text = "Profiles";
      this.ContextMenuStrip1.ResumeLayout(false);
      this.GroupBox2.ResumeLayout(false);
      this.DbLayoutPanel1.ResumeLayout(false);
      this.DbLayoutPanel1.PerformLayout();
      this.ResumeLayout(false);
      this.ResumeLayout(false);
      this.PerformLayout();
      this.Button1.Click += new System.EventHandler(this.Button1_Click);
      this.Button2.Click += new System.EventHandler(this.Button2_Click);
      this.Button3.Click += new System.EventHandler(this.Button3_Click);
      this.ListView1.DrawColumnHeader += new System.Windows.Forms.DrawListViewColumnHeaderEventHandler(this.ListView1_DrawColumnHeader);
      this.ListView1.DrawItem += new System.Windows.Forms.DrawListViewItemEventHandler(this.ListView1_DrawItem);
      this.ListView1.DrawSubItem += new System.Windows.Forms.DrawListViewSubItemEventHandler(this.ListView1_DrawSubItem);
      this.ListView1.MouseHover += new System.EventHandler(this.ListView1_MouseHover);
      this.ListView1.Click += new System.EventHandler(this.ListView1_Click);
      this.ListView1.DoubleClick += new System.EventHandler(this.ListView1_DoubleClick);
      this.ListView1.MouseMove += new System.Windows.Forms.MouseEventHandler(this.ListView1_MouseMove);
      this.ContextMenuStrip1.Opening += new System.ComponentModel.CancelEventHandler(this.ContextMenuStrip1_Opening);
      this.ContextMenuStrip1.MouseLeave += new System.EventHandler(this.ContextMenuStrip1_MouseLeave);
      this.ToolStripMenuItem3.Click += new System.EventHandler(this.ToolStripMenuItem3_Click);
      this.ToolStripMenuItem4.Click += new System.EventHandler(this.ToolStripMenuItem4_Click);
      this.ToolStripMenuItem5.Click += new System.EventHandler(this.ToolStripMenuItem5_Click);
      this.ToolStripMenuItem6.Click += new System.EventHandler(this.ToolStripMenuItem6_Click);
      this.LaunchAppToolStripMenuItem.Click += new System.EventHandler(this.LaunchAppToolStripMenuItem_Click);
      this.LaunchAppWithOptionsToolStripMenuItem.Click += new System.EventHandler(this.LaunchAppWithOptionsToolStripMenuItem_Click);
      this.RemoveAllSelectedProfilesToolStripMenuItem.Click += new System.EventHandler(this.ToolStripMenuItem5_Click);
      this.CheckVoiceConfirm.CheckedChanged += new System.EventHandler(this.CheckVoiceConfirm_CheckedChanged);
      this.ComboResolution.SelectedIndexChanged += new System.EventHandler(this.ComboResolution_SelectedIndexChanged);
    
    }

        #endregion

    internal ListView ListView1;
    internal Button Button2;
    internal CheckBox CheckVoiceConfirm;
    internal ContextMenuStrip ContextMenuStrip1;
    internal ToolStripMenuItem ToolStripMenuItem3;
    internal ToolStripMenuItem ToolStripMenuItem4;
    internal ToolStripMenuItem ToolStripMenuItem5;
    internal ToolStripMenuItem LaunchAppToolStripMenuItem;
    internal ToolStripMenuItem LaunchAppWithOptionsToolStripMenuItem;
    internal Button Button1;
    internal ToolStripMenuItem ToolStripMenuItem6;
    internal ComboBox ComboResolution;
    internal Button Button3;
        internal ColumnHeader ColumnHeader1;
        internal ColumnHeader ColumnHeader2;
        internal ColumnHeader ColumnHeader3;
        internal ColumnHeader ColumnHeader4;
        internal ColumnHeader ColumnHeader5;
        internal ToolStripMenuItem ToolStripMenuItem1;
        internal ToolStripMenuItem ToolStripMenuItem2;
        internal ToolStripSeparator ToolStripSeparator1;
        internal ToolStripSeparator ToolStripSeparator2;
        internal ToolStripSeparator ToolStripSeparator3;
        internal ToolStripMenuItem RemoveAllSelectedProfilesToolStripMenuItem;
        internal GroupBox GroupBox2;
        internal Label Label2;
        internal Label Label1;
        internal Label Label3;
        internal Label Label4;
        internal Label Label5;
        internal Label Label16;
        internal Label Label17;
        internal Label Label18;
        internal Label Label19;
        internal Label Label20;
        internal Label Label22;
        internal Label Label23;
        internal Label Label24;
        internal Label Label25;
        internal Label Label26;
        internal Label Label27;
        internal Label Label28;
        internal Label Label30;
        internal Label Label29;
        internal Label Label15;
        internal Label Label14;
        internal Label Label13;
        internal Label Label12;
        internal Label Label11;
        internal Label Label10;
        internal Label Label9;
        internal Label Label8;
        internal Label Label7;
        internal Label Label6;
        internal Label Label31;
        internal Label Label32;
        internal TextBox TextBox1;
        internal ToolTip ToolTip1;
        internal DBLayoutPanel DbLayoutPanel1;
    
    }
}