using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using System.Management;

namespace MetaQuestTrayTool.Forms
{
    partial class frmVoiceSettings
    {
        private System.ComponentModel.IContainer components = null;

protected override void Dispose(bool disposing)
    {
      try
      {
        if (!disposing || this.components == null)
          return;
        this.components.Dispose();
      }
      finally
      {
        base.Dispose(disposing);
      }
    }

        #region Windows Form Designer generated code

    private void InitializeComponent()
    {
      this.components = (IContainer) new System.ComponentModel.Container();
      System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof (frmVoiceSettings));
      this.GroupBox1 = new GroupBox();
      this.Label2 = new Label();
      this.Button1 = new Button();
      this.ToolTip1 = new ToolTip(this.components);
      this.Button3 = new Button();
      this.LabelConfidencePercent = new Label();
      this.Label1 = new Label();
      this.TrackBar1 = new TrackBar();
      this.ImageList1 = new ImageList(this.components);
      this.DotNetBarTabcontrol1 = new DotNetBarTabcontrol();
      this.TabPage3 = new TabPage();
      this.GroupBox2 = new GroupBox();
      this.CheckBox7 = new CheckBox();
      this.CheckBox5 = new CheckBox();
      this.CheckBox6 = new CheckBox();
      this.Label3 = new Label();
      this.LabelExplain = new Label();
      this.LabelKey = new Label();
      this.CheckBox1 = new CheckBox();
      this.ButtonListen = new Button();
      this.CheckBox2 = new CheckBox();
      this.Label4 = new Label();
      this.CheckBox3 = new CheckBox();
      this.ComboDevice = new ComboBox();
      this.CheckBox4 = new CheckBox();
      this.TabPage1 = new TabPage();
      this.ListView1 = new ListView();
      this.ColumnHeader1 = new ColumnHeader();
      this.ColumnHeader2 = new ColumnHeader();
      this.ColumnHeader3 = new ColumnHeader();
      this.TabPage2 = new TabPage();
      this.Button4 = new Button();
      this.Button2 = new Button();
      this.ComboBox1 = new ComboBox();
      this.Label5 = new Label();
      this.ListView2 = new ListView();
      this.ColumnHeader4 = new ColumnHeader();
      this.ColumnHeader5 = new ColumnHeader();
      this.GroupBox1.SuspendLayout();
      this.TrackBar1.BeginInit();
      this.DotNetBarTabcontrol1.SuspendLayout();
      this.TabPage3.SuspendLayout();
      this.GroupBox2.SuspendLayout();
      this.TabPage1.SuspendLayout();
      this.TabPage2.SuspendLayout();
      this.SuspendLayout();
      this.GroupBox1.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.GroupBox1.Controls.Add(this.Label2);
      this.GroupBox1.ForeColor = Color.DodgerBlue;
      this.GroupBox1.Location = new Point(12, 12);
      this.GroupBox1.Name = "GroupBox1";
      this.GroupBox1.Size = new Size(601, 47);
      this.GroupBox1.TabIndex = 0;
      this.GroupBox1.TabStop = false;
      this.Label2.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.Label2.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Label2.ForeColor = Color.DodgerBlue;
      this.Label2.Location = new Point(5, 10);
      this.Label2.Name = "Label2";
      this.Label2.Size = new Size(585, 35);
      this.Label2.TabIndex = 0;
      this.Label2.Text = "Click on the Voice Command you want to edit and add/remove phrases to control that function. Commands are separated with a semicolon ( ; ).\r\n";
      this.Button1.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
      this.Button1.FlatStyle = FlatStyle.Flat;
      this.Button1.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Button1.ForeColor = Color.DodgerBlue;
      this.Button1.Location = new Point(538, 474);
      this.Button1.Name = "Button1";
      this.Button1.Size = new Size(75, 25);
      this.Button1.TabIndex = 5;
      this.Button1.Text = "OK";
      this.Button1.UseVisualStyleBackColor = true;
      this.Button3.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.Button3.FlatStyle = FlatStyle.Flat;
      this.Button3.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Button3.ForeColor = Color.DodgerBlue;
      this.Button3.Location = new Point(12, 474);
      this.Button3.Name = "Button3";
      this.Button3.Size = new Size(83, 25);
      this.Button3.TabIndex = 10;
      this.Button3.Text = "Set Defaults";
      this.Button3.UseVisualStyleBackColor = true;
      this.LabelConfidencePercent.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.LabelConfidencePercent.AutoSize = true;
      this.LabelConfidencePercent.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.LabelConfidencePercent.ForeColor = Color.DodgerBlue;
      this.LabelConfidencePercent.Location = new Point(308, 479);
      this.LabelConfidencePercent.Name = "LabelConfidencePercent";
      this.LabelConfidencePercent.Size = new Size(0, 15);
      this.LabelConfidencePercent.TabIndex = 40;
      this.Label1.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.Label1.AutoSize = true;
      this.Label1.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Label1.ForeColor = Color.DodgerBlue;
      this.Label1.Location = new Point(126, 479);
      this.Label1.Name = "Label1";
      this.Label1.Size = new Size(72, 15);
      this.Label1.TabIndex = 39;
      this.Label1.Text = "Confidence:";
      this.TrackBar1.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.TrackBar1.AutoSize = false;
      this.TrackBar1.Location = new Point(201, 479);
      this.TrackBar1.Maximum = 100;
      this.TrackBar1.Minimum = 1;
      this.TrackBar1.Name = "TrackBar1";
      this.TrackBar1.Size = new Size(107, 20);
      this.TrackBar1.TabIndex = 38;
      this.TrackBar1.TickStyle = TickStyle.None;
      this.TrackBar1.Value = 1;
      this.ImageList1.ImageStream = (ImageListStreamer) resources.GetObject("ImageList1.ImageStream");
      this.ImageList1.TransparentColor = Color.Transparent;
      this.ImageList1.Images.SetKeyName(0, "Very-Basic-Listen-icon.png");
      this.ImageList1.Images.SetKeyName(1, "Very-Basic-Not-Listen-icon.png");
      this.DotNetBarTabcontrol1.Alignment = TabAlignment.Left;
      this.DotNetBarTabcontrol1.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
      this.DotNetBarTabcontrol1.Controls.Add(this.TabPage3);
      this.DotNetBarTabcontrol1.Controls.Add(this.TabPage1);
      this.DotNetBarTabcontrol1.Controls.Add(this.TabPage2);
      this.DotNetBarTabcontrol1.ItemSize = new Size(43, 80);
      this.DotNetBarTabcontrol1.Location = new Point(12, 65);
      this.DotNetBarTabcontrol1.Multiline = true;
      this.DotNetBarTabcontrol1.Name = "DotNetBarTabcontrol1";
      this.DotNetBarTabcontrol1.SelectedIndex = 0;
      this.DotNetBarTabcontrol1.Size = new Size(601, 403);
      this.DotNetBarTabcontrol1.SizeMode = TabSizeMode.Fixed;
      this.DotNetBarTabcontrol1.TabIndex = 41;
      this.ToolTip1.SetToolTip(this.DotNetBarTabcontrol1, "Click to add command");
      this.TabPage3.BackColor = Color.White;
      this.TabPage3.Controls.Add(this.GroupBox2);
      this.TabPage3.Location = new Point(84, 4);
      this.TabPage3.Name = "TabPage3";
      this.TabPage3.Padding = new Padding(3);
      this.TabPage3.Size = new Size(513, 395);
      this.TabPage3.TabIndex = 2;
      this.TabPage3.Text = "Activation";
      this.GroupBox2.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
      this.GroupBox2.Controls.Add(this.CheckBox7);
      this.GroupBox2.Controls.Add(this.CheckBox5);
      this.GroupBox2.Controls.Add(this.CheckBox6);
      this.GroupBox2.Controls.Add(this.Label3);
      this.GroupBox2.Controls.Add(this.LabelExplain);
      this.GroupBox2.Controls.Add(this.LabelKey);
      this.GroupBox2.Controls.Add(this.CheckBox1);
      this.GroupBox2.Controls.Add(this.ButtonListen);
      this.GroupBox2.Controls.Add(this.CheckBox2);
      this.GroupBox2.Controls.Add(this.Label4);
      this.GroupBox2.Controls.Add(this.CheckBox3);
      this.GroupBox2.Controls.Add(this.ComboDevice);
      this.GroupBox2.Controls.Add(this.CheckBox4);
      this.GroupBox2.Location = new Point(6, 0);
      this.GroupBox2.Name = "GroupBox2";
      this.GroupBox2.Size = new Size(501, 389);
      this.GroupBox2.TabIndex = 10;
      this.GroupBox2.TabStop = false;
      this.CheckBox7.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
      this.CheckBox7.AutoSize = true;
      this.CheckBox7.ForeColor = Color.DodgerBlue;
      this.CheckBox7.Location = new Point(355, 366);
      this.CheckBox7.Name = "CheckBox7";
      this.CheckBox7.Size = new Size(138, 17);
      this.CheckBox7.TabIndex = 12;
      this.CheckBox7.Text = "Disable audio feedback";
      this.CheckBox7.UseVisualStyleBackColor = true;
      this.CheckBox5.AutoSize = true;
      this.CheckBox5.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.CheckBox5.ForeColor = Color.DodgerBlue;
      this.CheckBox5.Location = new Point(20, 162);
      this.CheckBox5.Name = "CheckBox5";
      this.CheckBox5.Size = new Size(178, 19);
      this.CheckBox5.TabIndex = 10;
      this.CheckBox5.Text = "Joystick activated, continous";
      this.CheckBox5.UseVisualStyleBackColor = true;
      this.CheckBox6.AutoSize = true;
      this.CheckBox6.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.CheckBox6.ForeColor = Color.DodgerBlue;
      this.CheckBox6.Location = new Point(20, 187);
      this.CheckBox6.Name = "CheckBox6";
      this.CheckBox6.Size = new Size(198, 19);
      this.CheckBox6.TabIndex = 11;
      this.CheckBox6.Text = "Joystick activated, Push-To-Talk";
      this.CheckBox6.UseVisualStyleBackColor = true;
      this.Label3.AutoSize = true;
      this.Label3.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Label3.ForeColor = Color.DodgerBlue;
      this.Label3.Location = new Point(6, 30);
      this.Label3.Name = "Label3";
      this.Label3.Size = new Size(446, 15);
      this.Label3.TabIndex = 0;
      this.Label3.Text = "Select how voice commands should be enabled. You can select multiple options.";
      this.LabelExplain.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.LabelExplain.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.LabelExplain.ForeColor = Color.DodgerBlue;
      this.LabelExplain.Location = new Point(256, 70);
      this.LabelExplain.Name = "LabelExplain";
      this.LabelExplain.Size = new Size(239, 178);
      this.LabelExplain.TabIndex = 2;
      this.LabelKey.Font = new Font("Microsoft Sans Serif", 15.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.LabelKey.ForeColor = Color.DodgerBlue;
      this.LabelKey.Location = new Point(19, 324);
      this.LabelKey.Name = "LabelKey";
      this.LabelKey.Size = new Size(205, 25);
      this.LabelKey.TabIndex = 9;
      this.LabelKey.TextAlign = ContentAlignment.MiddleCenter;
      this.CheckBox1.AutoSize = true;
      this.CheckBox1.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.CheckBox1.ForeColor = Color.DodgerBlue;
      this.CheckBox1.Location = new Point(20, 70);
      this.CheckBox1.Name = "CheckBox1";
      this.CheckBox1.Size = new Size(166, 19);
      this.CheckBox1.TabIndex = 1;
      this.CheckBox1.Text = "Voice activated, continous";
      this.CheckBox1.UseVisualStyleBackColor = true;
      this.ButtonListen.Enabled = false;
      this.ButtonListen.FlatStyle = FlatStyle.Flat;
      this.ButtonListen.Image = (Image) (System.Drawing.Image)MetaQuestTrayTool.My.Resources.Resources.Very_Basic_Not_Listen_icon;
      this.ButtonListen.Location = new Point(242, 313);
      this.ButtonListen.Name = "ButtonListen";
      this.ButtonListen.Size = new Size(56, 53);
      this.ButtonListen.TabIndex = 8;
      this.ToolTip1.SetToolTip(this.ButtonListen, "Click to capture button or key");
      this.ButtonListen.UseVisualStyleBackColor = true;
      this.CheckBox2.AutoSize = true;
      this.CheckBox2.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.CheckBox2.ForeColor = Color.DodgerBlue;
      this.CheckBox2.Location = new Point(20, 93);
      this.CheckBox2.Name = "CheckBox2";
      this.CheckBox2.Size = new Size(162, 19);
      this.CheckBox2.TabIndex = 3;
      this.CheckBox2.Text = "Voice activated, repeated";
      this.CheckBox2.UseVisualStyleBackColor = true;
      this.Label4.AutoSize = true;
      this.Label4.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Label4.ForeColor = Color.DodgerBlue;
      this.Label4.Location = new Point(16, 247);
      this.Label4.Name = "Label4";
      this.Label4.Size = new Size(208, 15);
      this.Label4.TabIndex = 7;
      this.Label4.Text = "Select device for button/key activation";
      this.CheckBox3.AutoSize = true;
      this.CheckBox3.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.CheckBox3.ForeColor = Color.DodgerBlue;
      this.CheckBox3.Location = new Point(20, 116);
      this.CheckBox3.Name = "CheckBox3";
      this.CheckBox3.Size = new Size(188, 19);
      this.CheckBox3.TabIndex = 4;
      this.CheckBox3.Text = "Keyboard activated, continous";
      this.CheckBox3.UseVisualStyleBackColor = true;
      this.ComboDevice.Enabled = false;
      this.ComboDevice.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.ComboDevice.ForeColor = Color.DodgerBlue;
      this.ComboDevice.FormattingEnabled = true;
      this.ComboDevice.Location = new Point(19, 265);
      this.ComboDevice.Name = "ComboDevice";
      this.ComboDevice.Size = new Size(205, 23);
      this.ComboDevice.TabIndex = 6;
      this.CheckBox4.AutoSize = true;
      this.CheckBox4.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.CheckBox4.ForeColor = Color.DodgerBlue;
      this.CheckBox4.Location = new Point(20, 139);
      this.CheckBox4.Name = "CheckBox4";
      this.CheckBox4.Size = new Size(208, 19);
      this.CheckBox4.TabIndex = 5;
      this.CheckBox4.Text = "Keyboard activated, Push-To-Talk";
      this.CheckBox4.UseVisualStyleBackColor = true;
      this.TabPage1.BackColor = Color.White;
      this.TabPage1.Controls.Add(this.ListView1);
      this.TabPage1.Location = new Point(84, 4);
      this.TabPage1.Name = "TabPage1";
      this.TabPage1.Padding = new Padding(3);
      this.TabPage1.Size = new Size(513, 395);
      this.TabPage1.TabIndex = 0;
      this.TabPage1.Text = "System";
      this.ListView1.Columns.AddRange(new ColumnHeader[3]
      {
        this.ColumnHeader1,
        this.ColumnHeader2,
        this.ColumnHeader3
      });
      this.ListView1.Dock = DockStyle.Fill;
      this.ListView1.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.ListView1.ForeColor = Color.DodgerBlue;
      this.ListView1.FullRowSelect = true;
      this.ListView1.GridLines = true;
      this.ListView1.Location = new Point(3, 3);
      this.ListView1.Name = "ListView1";
      this.ListView1.Size = new Size(507, 389);
      this.ListView1.TabIndex = 1;
      this.ListView1.UseCompatibleStateImageBehavior = false;
      this.ListView1.View = View.Details;
      this.ColumnHeader1.Text = "Action";
      this.ColumnHeader1.Width = 134;
      this.ColumnHeader2.Text = "Voice Command";
      this.ColumnHeader2.Width = 187;
      this.ColumnHeader3.Text = "Enabled";
      this.TabPage2.BackColor = Color.White;
      this.TabPage2.Controls.Add(this.Button4);
      this.TabPage2.Controls.Add(this.Button2);
      this.TabPage2.Controls.Add(this.ComboBox1);
      this.TabPage2.Controls.Add(this.Label5);
      this.TabPage2.Controls.Add(this.ListView2);
      this.TabPage2.Location = new Point(84, 4);
      this.TabPage2.Name = "TabPage2";
      this.TabPage2.Padding = new Padding(3);
      this.TabPage2.Size = new Size(513, 395);
      this.TabPage2.TabIndex = 1;
      this.TabPage2.Text = "User";
      this.Button4.FlatStyle = FlatStyle.Flat;
      this.Button4.ForeColor = Color.DodgerBlue;
      this.Button4.Location = new Point(299, 7);
      this.Button4.Name = "Button4";
      this.Button4.Size = new Size(75, 23);
      this.Button4.TabIndex = 4;
      this.Button4.Text = "Add Profile";
      this.Button4.UseVisualStyleBackColor = true;
      this.Button2.Enabled = false;
      this.Button2.FlatStyle = FlatStyle.Flat;
      this.Button2.ForeColor = Color.DodgerBlue;
      this.Button2.Location = new Point(218, 7);
      this.Button2.Name = "Button2";
      this.Button2.Size = new Size(75, 23);
      this.Button2.TabIndex = 3;
      this.Button2.Text = "Edit Profile";
      this.Button2.UseVisualStyleBackColor = true;
      this.ComboBox1.ForeColor = Color.DodgerBlue;
      this.ComboBox1.FormattingEnabled = true;
      this.ComboBox1.Location = new Point(48, 9);
      this.ComboBox1.Name = "ComboBox1";
      this.ComboBox1.Size = new Size(164, 21);
      this.ComboBox1.TabIndex = 2;
      this.Label5.AutoSize = true;
      this.Label5.ForeColor = Color.DodgerBlue;
      this.Label5.Location = new Point(6, 12);
      this.Label5.Name = "Label5";
      this.Label5.Size = new Size(36, 13);
      this.Label5.TabIndex = 1;
      this.Label5.Text = "Profile";
      this.ListView2.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
      this.ListView2.Columns.AddRange(new ColumnHeader[2]
      {
        this.ColumnHeader4,
        this.ColumnHeader5
      });
      this.ListView2.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.ListView2.ForeColor = Color.DodgerBlue;
      this.ListView2.FullRowSelect = true;
      this.ListView2.GridLines = true;
      this.ListView2.Location = new Point(3, 38);
      this.ListView2.Name = "ListView2";
      this.ListView2.Size = new Size(507, 354);
      this.ListView2.TabIndex = 0;
      this.ListView2.UseCompatibleStateImageBehavior = false;
      this.ListView2.View = View.Details;
      this.ColumnHeader4.Text = "Spoken Command";
      this.ColumnHeader4.Width = 264;
      this.ColumnHeader5.Text = "Actions";
      this.ColumnHeader5.Width = 227;
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.AutoSizeMode = AutoSizeMode.GrowAndShrink;
      this.BackColor = Color.White;
      this.ClientSize = new Size(625, 508);
      this.Controls.Add(this.DotNetBarTabcontrol1);
      this.Controls.Add(this.LabelConfidencePercent);
      this.Controls.Add(this.Label1);
      this.Controls.Add(this.TrackBar1);
      this.Controls.Add(this.Button3);
      this.Controls.Add(this.Button1);
      this.Controls.Add(this.GroupBox1);
      this.Icon = (Icon) resources.GetObject("$this.Icon");
      this.KeyPreview = true;
      this.MaximizeBox = false;
      this.MinimizeBox = false;
      this.Name = "frmVoiceSettings";
      this.StartPosition = FormStartPosition.CenterParent;
      this.Text = "Configure Voice Commands";
      this.GroupBox1.ResumeLayout(false);
      this.TrackBar1.EndInit();
      this.DotNetBarTabcontrol1.ResumeLayout(false);
      this.TabPage3.ResumeLayout(false);
      this.GroupBox2.ResumeLayout(false);
      this.GroupBox2.PerformLayout();
      this.Button1.Click += new System.EventHandler(this.Button1_Click);
      this.Button3.Click += new System.EventHandler(this.Button3_Click);
      this.TrackBar1.Scroll += new System.EventHandler(this.TrackBar1_Scroll);
      this.TrackBar1.MouseUp += new System.Windows.Forms.MouseEventHandler(this.TrackBar1_MouseUp);
      this.CheckBox1.CheckedChanged += new System.EventHandler(this.CheckBox1_CheckedChanged);
      this.CheckBox1.MouseHover += new System.EventHandler(this.CheckBox1_MouseHover);
      this.CheckBox2.CheckedChanged += new System.EventHandler(this.CheckBox2_CheckedChanged);
      this.CheckBox2.MouseHover += new System.EventHandler(this.CheckBox2_MouseHover);
      this.CheckBox3.CheckedChanged += new System.EventHandler(this.CheckBox3_CheckedChanged);
      this.CheckBox3.MouseHover += new System.EventHandler(this.CheckBox3_MouseHover);
      this.CheckBox4.CheckedChanged += new System.EventHandler(this.CheckBox4_CheckedChanged);
      this.CheckBox4.MouseHover += new System.EventHandler(this.CheckBox4_MouseHover);
      this.CheckBox5.CheckedChanged += new System.EventHandler(this.CheckBox5_CheckedChanged);
      this.CheckBox5.MouseHover += new System.EventHandler(this.CheckBox5_MouseHover);
      this.CheckBox6.CheckedChanged += new System.EventHandler(this.CheckBox6_CheckedChanged);
      this.CheckBox6.MouseHover += new System.EventHandler(this.CheckBox6_MouseHover);
      this.CheckBox7.CheckedChanged += new System.EventHandler(this.CheckBox7_CheckedChanged);
      this.ButtonListen.Click += new System.EventHandler(this.ButtonListen_Click);
      this.ComboDevice.SelectedIndexChanged += new System.EventHandler(this.ComboDevice_SelectedIndexChanged);
      this.ComboDevice.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.ComboDevice_KeyPress);
      this.ListView1.MouseClick += new System.Windows.Forms.MouseEventHandler(this.ListView1_MouseClick);
      this.Button4.Click += new System.EventHandler(this.Button4_Click);
      this.Button2.Click += new System.EventHandler(this.Button2_Click);
      this.ComboBox1.SelectedIndexChanged += new System.EventHandler(this.ComboBox1_SelectedIndexChanged);
      this.ComboBox1.TextChanged += new System.EventHandler(this.ComboBox1_TextChanged);
      this.DotNetBarTabcontrol1.SelectedIndexChanged += new System.EventHandler(this.DotNetBarTabcontrol1_SelectedIndexChanged);
      this.TabPage1.ResumeLayout(false);
      this.TabPage2.ResumeLayout(false);
      this.TabPage2.PerformLayout();
      this.ResumeLayout(false);
      this.PerformLayout();
    
    }

        #endregion

    internal Button Button1;
    internal Button Button3;
    internal TrackBar TrackBar1;
    internal ListView ListView1;
    internal CheckBox CheckBox1;
    internal CheckBox CheckBox2;
    internal CheckBox CheckBox4;
    internal CheckBox CheckBox3;
    internal ComboBox ComboDevice;
    internal Button ButtonListen;
    internal CheckBox CheckBox5;
    internal CheckBox CheckBox6;
    internal CheckBox CheckBox7;
    internal ComboBox ComboBox1;
    internal Button Button4;
    internal Button Button2;
        internal GroupBox GroupBox1;
        internal Label Label2;
        internal Label LabelConfidencePercent;
        internal Label Label1;
        internal DotNetBarTabcontrol DotNetBarTabcontrol1;
        internal TabPage TabPage3;
        internal GroupBox GroupBox2;
        internal Label Label3;
        internal Label LabelExplain;
        internal Label LabelKey;
        internal Label Label4;
        internal TabPage TabPage1;
        internal ColumnHeader ColumnHeader1;
        internal ColumnHeader ColumnHeader2;
        internal ColumnHeader ColumnHeader3;
        internal TabPage TabPage2;
        internal Label Label5;
        internal ListView ListView2;
        internal ColumnHeader ColumnHeader4;
        internal ColumnHeader ColumnHeader5;
        internal ToolTip ToolTip1;
        internal ImageList ImageList1;
    
    }
}
